import { writeFile, readFile, mkdir, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

import { MAP_BOUNDS, SVG_WIDTH, SVG_HEIGHT, PADDING } from '../browserbible/js/windows/MapWindow/constants.js';
import { buildRelief } from './relief.mjs';
import { polygonLayerPath, riverLayerPath } from './basemap-paths.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, '..');
const OUT = join(REPO, 'browserbible/public/content/maps/biblical-map.svg');
const RELIEF_AVIF = join(REPO, 'browserbible/public/content/maps/relief.avif');
const RELIEF_WEBP = join(REPO, 'browserbible/public/content/maps/relief.webp');
const RELIEF_HREF = 'content/maps/relief.avif';
const RELIEF_HREF_WEBP = 'content/maps/relief.webp';
const CACHE_DIR = join(tmpdir(), 'browserbible-basemap-cache', 'natural-earth');

const NE_BASE = 'https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/10m/physical';
const LAYERS = {
  land: 'ne_10m_land',
  lakes: 'ne_10m_lakes',
  rivers: 'ne_10m_rivers_lake_centerlines'
};

async function loadLayer(key) {
  await mkdir(CACHE_DIR, { recursive: true });
  const file = join(CACHE_DIR, `${LAYERS[key]}.json`);
  try {
    await access(file);
  } catch {
    const url = `${NE_BASE}/${LAYERS[key]}.json`;
    process.stdout.write(`  fetching ${url}\n`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
    await writeFile(file, await res.text());
  }
  return JSON.parse(await readFile(file, 'utf8'));
}

async function main() {
  process.stdout.write('Loading Natural Earth layers…\n');
  const [land, lakes, rivers] = await Promise.all([
    loadLayer('land'), loadLayer('lakes'), loadLayer('rivers')
  ]);

  const W = +SVG_WIDTH.toFixed(2);
  const H = +SVG_HEIGHT.toFixed(2);
  const contentX = PADDING;
  const contentY = PADDING;
  const contentW = +(SVG_WIDTH - 2 * PADDING).toFixed(2);
  const contentH = +(SVG_HEIGHT - 2 * PADDING).toFixed(2);

  const landPath = polygonLayerPath(land);
  const lakePath = polygonLayerPath(lakes);
  const riverPath = riverLayerPath(rivers);

  process.stdout.write(`  land rings: ${landPath.rings}, lake rings: ${lakePath.rings}, river segments: ${riverPath.segs}\n`);

  await buildRelief({ outputs: [
    { path: RELIEF_AVIF, quality: 55 },
    { path: RELIEF_WEBP, quality: 58 }
  ] });

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg id="map-svg" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by tools/build-basemap.mjs from Natural Earth 10m physical data + Terrarium relief. -->
  <!-- Corrected equirectangular projection (standard parallel ${(MAP_BOUNDS.minLat + MAP_BOUNDS.maxLat) / 2}°N) via geoToSvg(). -->
  <defs>
    <linearGradient id="seaGradient" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#bfe0ef"/>
      <stop offset="100%" stop-color="#8fbdd9"/>
    </linearGradient>
    <linearGradient id="landGradient" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#ecdcb0"/>
      <stop offset="100%" stop-color="#dac99c"/>
    </linearGradient>
    <clipPath id="content-clip">
      <rect x="${contentX}" y="${contentY}" width="${contentW}" height="${contentH}"/>
    </clipPath>
    <!-- Land geometry stored once; referenced via <use> for clip, fill and outline. -->
    <path id="land-shape" d="${landPath.d}"/>
    <clipPath id="land-clip">
      <use href="#land-shape"/>
    </clipPath>
  </defs>

  <rect x="0" y="0" width="${W}" height="${H}" fill="url(#seaGradient)"/>

  <g clip-path="url(#content-clip)">
    <rect x="${contentX}" y="${contentY}" width="${contentW}" height="${contentH}" fill="url(#seaGradient)"/>
    <!-- Flat land fill is the fallback while the relief lazy-loads (or if it can't). -->
    <use href="#land-shape" fill="url(#landGradient)"/>
    <!-- Relief is lazy-loaded: MapPanel probes AVIF support and sets href from
         data-src (AVIF) or data-src-fallback (WebP) after first paint. -->
    <image id="relief-layer" data-src="${RELIEF_HREF}" data-src-fallback="${RELIEF_HREF_WEBP}"
           x="${contentX}" y="${contentY}" width="${contentW}" height="${contentH}"
           preserveAspectRatio="none" clip-path="url(#land-clip)"/>
    <path d="${lakePath.d}" fill="#9fc8df" stroke="#7fb0cf" stroke-width="0.4"/>
    <path d="${riverPath.d}" fill="none" stroke="#8fb8d2" stroke-width="0.7" stroke-linecap="round" stroke-linejoin="round"/>
    <!-- Crisp coastline on top of the relief. -->
    <use href="#land-shape" fill="none" stroke="#9c8a5c" stroke-width="0.5"/>
  </g>

  <rect x="${contentX}" y="${contentY}" width="${contentW}" height="${contentH}" fill="none" stroke="#9a8a5e" stroke-width="1"/>
</svg>
`;

  await writeFile(OUT, svg);
  const kb = (Buffer.byteLength(svg) / 1024).toFixed(0);
  process.stdout.write(`Wrote ${OUT} (${kb} KB)\n`);
}

main().catch(err => { console.error(err); process.exit(1); });
