/**
 * Pericope source data — `reference: title` pairs in canonical order.
 *
 * Reference is the internal 2-char book shortCode followed by
 * `chapter.verse` (e.g. "GN1.1" = Genesis 1:1, "S116.14" = 1 Samuel 16:14).
 * Numbered books carry a digit in the code (S1, S2, K1, K2, R1, R2, ...).
 *
 * Parsed into navigable records by Pericopes.js.
 */
export const PERICOPE_DATA = {
  "GN1.1": "Creation",
  "GN2.4": "The First Humans",
  "GN2.8": "The Garden of Eden",
  "GN3.1": "The Sin of Adam and Eve",
  "GN4.1": "Cain Murders Able",
  "GN4.16": "The Family of Cain",
  "GN4.25": "The Family of Adam",
  "GN6.1": "The Wickedness of Man",
  "GN6.9": "Noah's Ark",
  "GN7.11": "The Great Flood",
  "GN8.20": "God’s Covenant with Noah",
  "GN9.18": "Noah and His Sons",
  "GN10.1": "The Descendants of Noah",
  "GN11.1": "The Tower of Babel",
  "GN11.10": "The Descendants of Shem",
  "GN11.27": "The Descendants of Terah",
  "GN12.1": "God’s Promise to Abram",
  "GN12.10": "Abram in Egypt",
  "GN13.1": "Abram and Lot Separate",
  "GN14.1": "The Captivity and Rescue of Lot",
  "GN14.18": "Melchizedek King of Salem",
  "GN15.1": "God’s Covenant with Abram",
  "GN16.1": "Hagar and Ishmael",
  "GN17.1": "The Sign of the Covenant",
  "GN18.1": "The Three Visitors",
  "GN19.1": "Sodom",
  "GN19.23": "The Destruction of Sodom and Gomorrah",
  "GN19.30": "The Descendants of Lot",
  "GN20.1": "Abimelech Marries Sara",
  "GN21.1": "The Birth of Isaac",
  "GN21.8": "Hagar and Ishmael Depart",
  "GN21.22": "A Covenant with Abimelech",
  "GN22.1": "God Tries Abraham’s Faith",
  "GN23.1": "Sarah’s Death and Funeral",
  "GN24.1": "Rebecca",
  "GN25.7": "The Death of Abraham",
  "GN25.29": "How Esau Sold his Birthright",
  "GN26.1": "Isaac and Abimelech",
  "GN26.15": "The Wells of Isaac",
  "GN27.1": "Isaac Blesses Jacob",
  "GN28.10": "Jacob’s Ladder",
  "GN29.1": "Rachel and Leah",
  "GN30.25": "Jacob’s Agreement with Laban",
  "GN31.1": "Jacob Flees from Laban",
  "GN32.22": "Jacob Wrestles with God",
  "GN33.1": "Jacob and Esau Meet",
  "GN34.1": "The Violation of Dinah",
  "GN35.1": "Jacob Returns to Bethel",
  "GN36.1": "Esau’s Family",
  "GN37.1": "Joseph the Dreamer",
  "GN38.1": "Judah and Tamar",
  "GN39.1": "Joseph in Potiphar's House",
  "GN40.1": "The Prisoner’s Dreams",
  "GN41.1": "Pharaoh’s Dream",
  "GN42.1": "Joseph’s Brothers Go to Egypt",
  "GN44.1": "Joseph’s Cup",
  "GN45.1": "How Joseph was Revealed to His Brothers",
  "GN46.1": "Jacob’s Journey to Egypt",
  "GN47.13": "The Famine Intensifies",
  "GN48.1": "Jacob Blesses Joseph’s Sons",
  "GN50.22": "The Death of Joseph",
  "EX1.1": "Israel Oppressed",
  "EX2.1": "The Birth of Moses",
  "EX3.1": "The Burning Bush",
  "EX4.18": "Moses Returns to Egypt",
  "EX6.14": "The Family of Moses and Aaron",
  "EX7.8": "The Serpent Rods",
  "EX7.14": "The 1st Plague, Water Becomes Blood",
  "EX8.1": "The 2nd Plague, Frogs",
  "EX8.16": "The 3rd Plague, Lice",
  "EX8.20": "The 4th Plague, Flies",
  "EX9.1": "The 5th Plague, The Livestock’s Blight",
  "EX9.8": "The 6th Plague, Boils",
  "EX9.13": "The 7th Plague, Hail",
  "EX10.1": "The 8th Plague, Locusts",
  "EX10.21": "The 9th Plague, Darkness",
  "EX12.1": "Passover",
  "EX12.29": "The Death of the First Borne",
  "EX12.31": "Exodus",
  "EX13.1": "The Consecration of the First Born",
  "EX13.17": "The Pillars of Cloud and Fire",
  "EX14.1": "The Red Sea",
  "EX15.22": "The Bitter Waters Made Sweet",
  "EX16.1": "Manna from Heaven",
  "EX17.1": "Water from the Rock",
  "EX17.8": "Victory over the Amalekites",
  "EX18.1": "Jethro’s Advice",
  "EX19.1": "Mount Sinai",
  "EX20.1": "The Ten Commandments",
  "EX20.22": "The Law of the Alter",
  "EX21.1": "The Law Concerning Servants",
  "EX21.12": "The Law Concerning Violence",
  "EX21.28": "Animal Control Laws",
  "EX22.1": "Responsibility for Property",
  "EX22.16": "Justice",
  "EX23.10": "The Sabbath and Feasts",
  "EX24.1": "The Covenant Confirmed",
  "EX25.1": "A Contribution for the Sanctuary",
  "EX25.10": "The Ark of the Covenant",
  "EX25.23": "The Showbread Table",
  "EX25.31": "The Golden Lamp Stand",
  "EX26.1": "The Tabernacle",
  "EX27.1": "The Alter of Burnt Offering",
  "EX27.9": "The Court of the Tabernacle",
  "EX28.1": "The Garments of the Priesthood",
  "EX29.1": "The Consecration of the Priesthood",
  "EX29.38": "Daily Offerings",
  "EX30.1": "The Altar of Incense",
  "EX30.11": "The Ransom",
  "EX30.17": "The Bronze Laver",
  "EX30.22": "The Anointing Oil",
  "EX30.34": "The Incense",
  "EX31.1": "Craftsmen for the Building of the Temple",
  "EX31.12": "The Sabbath Law",
  "EX32.1": "The Golden Calf",
  "EX33.1": "Leaving Sinai",
  "EX33.7": "The Tent of Meeting",
  "EX34.29": "The Face of Moses",
  "EX35.1": "Building the Tabernacle",
  "EX40.34": "The Cloud and the Glory",
  "LV1.1": "The Burnt Offering",
  "LV2.1": "The Grain Offering",
  "LV3.1": "The Piece Offering",
  "LV4.1": "The Sin Offering",
  "LV5.1": "The Trespass Offering",
  "LV6.8": "The Law of the Burnt Offering",
  "LV6.14": "The Law of the Grain Offering",
  "LV6.24": "The Law of the Sin Offering",
  "LV7.1": "The Law of the Trespass Offering",
  "LV7.11": "The Law of the Peace Offering",
  "LV7.22": "Fat and Blood",
  "LV7.28": "The Priest’s Portion",
  "LV8.1": "The Consecration of the Priests",
  "LV9.1": "The Lord Accepts Aaron's Offering",
  "LV10.1": "Nadab, Abihu and the Profane Fire",
  "LV11.1": "Forbidden and Permitted Foods",
  "LV12.1": "Child Bearing Rituals",
  "LV13.1": "The Law Concerning Leprosy",
  "LV15.1": "The Law Concerning Bodily Discharges",
  "LV16.1": "The Day of Atonement",
  "LV17.1": "The Sanctity of Blood",
  "LV18.1": "Sexual Morality",
  "LV19.1": "Ceremonial Law",
  "LV20.1": "The Punishment for Child Sacrifice",
  "LV21.1": "The Conduct of Priests",
  "LV21.17": "Acceptable Offerings",
  "LV23.1": "The Feasts",
  "LV24.1": "The Care of the Lamps and Bread of the Tabernacle",
  "LV24.10": "Blasphemy",
  "LV24.17": "An Eye for an Eye",
  "LV25.1": "A Sabbath for the Land",
  "LV25.8": "The Year of Jubilee",
  "LV25.23": "Persons and Property",
  "LV26.1": "Blessings and Curses",
  "LV27.1": "The Law Concerning Vows",
  "NU1.1": "Israel’s First Census",
  "NU3.1": "The Levites",
  "NU4.1": "The Kohathite Duties",
  "NU5.1": "The Unclean are Isolated",
  "NU5.5": "Confession and Restitution",
  "NU5.11": "Concerning Unfaithful Wives",
  "NU6.1": "The Nazirite’s Oath",
  "NU6.22": "May the Lord Bless You",
  "NU7.1": "Offering of the Leaders",
  "NU8.1": "Arranging the Lamps",
  "NU8.5": "The Levite’s Cleansing and Dedication",
  "NU9.1": "Passover Remembered",
  "NU9.15": "The Cloud and the Fire",
  "NU10.1": "Two Silver Trumpets",
  "NU10.11": "Israel Leaves Sinai",
  "NU11.1": "The People Complain",
  "NU11.16": "The Seventy Elders",
  "NU11.31": "The Quail and the Plague",
  "NU12.1": "Aaron and Miriam’s Dissension",
  "NU13.1": "The Spies in Canaan",
  "NU14.1": "Refusing the Promised Land",
  "NU14.11": "Moses Intercedes for the People",
  "NU14.39": "A Failed Invasion",
  "NU15.1": "Grain and Drink Offerings",
  "NU15.22": "Unintentional Sin",
  "NU15.37": "The Tassel",
  "NU16.1": "Korah’s Rebellion",
  "NU17.1": "The Budding of Aaron’s Rod",
  "NU18.1": "The Office of the Priest",
  "NU19.1": "The Laws of Purification",
  "NU20.1": "The Death of Miriam",
  "NU20.2": "Water from the Rock",
  "NU20.14": "The Passage through Edom Refused",
  "NU20.22": "The Death of Aaron",
  "NU21.1": "Canaanites Defeated at Hormah",
  "NU21.4": "The Bronze Serpent",
  "NU21.21": "The Defeat of Sihon and Og",
  "NU22.1": "Balaam the Prophet",
  "NU25.1": "Israel’s Harlotry with Moab",
  "NU26.1": "Israel’s Second Census",
  "NU27.12": "The Inauguration of Joshua",
  "NU28.1": "The Offerings of God",
  "NU30.1": "The Law Concerning Vows",
  "NU31.1": "Vengeance On Midian",
  "NU32.1": "East of the Jordan",
  "NU33.1": "Remembering Egypt",
  "NU34.1": "The Boundaries of Canaan",
  "NU35.1": "Levite Cities",
  "NU35.9": "Cities of Refuge",
  "NU36.1": "The Marriage of Female Heirs",
  "DT1.1": "The Desert Years Remembered",
  "DT4.15": "The Sin of Idolatry",
  "DT4.41": "Cities of Refuge",
  "DT4.44": "The Law of God",
  "DT5.1": "The Ten Commandments",
  "DT6.1": "The Greatest Commandment",
  "DT7.1": "A Chosen People",
  "DT7.12": "The Blessing of Obedience",
  "DT8.1": "Remember the Lord Your God",
  "DT9.1": "Remembering the Rebellions",
  "DT10.1": "The Second Pair of Tablets",
  "DT12.1": "A Place of Worship",
  "DT13.1": "The Apostate’s Punishment",
  "DT14.1": "Improper Morning",
  "DT14.3": "Clean and Unclean Meats",
  "DT14.2": "The Tithe",
  "DT15.1": "Generosity",
  "DT15.19": "The Law Concerning First Born Animals",
  "DT16.1": "The Feasts Observed",
  "DT16.18": "The Sanctity of Justice",
  "DT17.14": "The Duty of Kings",
  "DT18.1": "The Priest’s Portion",
  "DT18.9": "The Abomination of Witchcraft",
  "DT18.15": "A Prophet Like Moses",
  "DT19.1": "Three Cities of Refuge",
  "DT20.1": "The Law Concerning War",
  "DT21.1": "The Law Concerning Unsolved Murder",
  "DT21.10": "The Treatment of Captured Women",
  "DT21.15": "The Rights of the First Born",
  "DT22.13": "Sexual Morality",
  "DT23.1": "Excluded People Groups",
  "DT23.9": "The Cleanliness of the Camp",
  "DT24.1": "The Law Concerning Divorce",
  "DT25.17": "Destroy the Amalekites",
  "DT26.1": "The Tithe and the First Fruits",
  "DT27.1": "The Law is Written in Stone",
  "DT27.11": "Mount Ebal and Mount Gerizim",
  "DT29.1": "The Renewed Covenant",
  "DT30.11": "Life or Death",
  "DT31.1": "Be Strong and of Good Courage",
  "DT31.30": "The Song of Moses",
  "DT34.1": "The Death of Moses",
  "JS1.1": "Be Strong and of Good Courage",
  "JS2.1": "How Rahab Hid the Spies",
  "JS3.1": "Crossing the Jordan",
  "JS4.1": "The Memorial Stones",
  "JS5.1": "The Second Generation is Circumcised",
  "JS5.13": "The Commander of the Army of the Lord",
  "JS6.1": "The Fall of Jericho",
  "JS7.1": "The Siege of Ai",
  "JS9.1": "The Treaty with Gibeon",
  "JS10.1": "The Sun Stands Still",
  "JS11.1": "The Conquest of Northern Canaan",
  "JS12.1": "The Conquered Kings",
  "JS13.1": "How the Tribes Divide the Land",
  "JS20.1": "The Cities of Refuge",
  "JS21.1": "The Levite Cities",
  "JS22.10": "An Alter by the Jordan",
  "JS23.1": "Joshua’s Farewell Address",
  "JS24.1": "The Covenant at Shechem",
  "JS24.29": "The Deaths of Joshua and Eleazar",
  "JG1.1": "The Conquest of Canaan",
  "JG2.1": "Israel’s Disobedience",
  "JG2.7": "The Death of Joshua",
  "JG3.7": "Othniel",
  "JG3.12": "Ehud",
  "JG3.31": "Shamgar",
  "JG4.1": "Deborah",
  "JG5.1": "The Song of Deborah",
  "JG6.1": "The Midianites Oppress Israel",
  "JG6.11": "Gideon",
  "JG6.28": "How Gideon Destroyed the Alter of Baal",
  "JG6.36": "The Sign of the Fleece",
  "JG7.1": "Gideon’s Three Hundred",
  "JG7.19": "The Battle with Midian",
  "JG9.1": "Abimelech’s Conspiracy",
  "JG9.7": "The Parable of the Trees",
  "JG9.22": "How Abimelech Fell",
  "JG10.1": "Tola",
  "JG10.3": "Jair",
  "JG11.1": "Jephthah and his Vow",
  "JG12.8": "Ibzan, Elon and Abdon",
  "JG13.1": "The Birth of Sampson",
  "JG14.1": "Sampson Marries a Philistine",
  "JG15.1": "The Jawbone of an Ass",
  "JG16.1": "Samson and Delilah",
  "JG16.23": "Samson Dies with the Philistines",
  "JG17.1": "Micah’s Idolatry",
  "JG19.1": "The Levite’s Concubine",
  "JG20.1": "The War With Benjamin",
  "JG21.1": "Wives for Benjamin",
  "RT1.1": "Elimelech’s Family",
  "RT1.6": "Naomi Returns with Ruth",
  "RT2.1": "Ruth and Boaz",
  "RT4.13": "The Descendant’s Of Ruth and Boaz",
  "S11.1": "The Family of Elkanah",
  "S12.1": "Hannah’s Prayer",
  "S12.12": "The Sons of Eli",
  "S13.1": "The Lord Speaks to Samuel",
  "S14.2": "How the Ark of God was Captured",
  "S14.12": "The Death of Eli",
  "S14.19": "Ichabod",
  "S15.1": "The Arch in Philistia",
  "S16.1": "The Ark Returned to Israel",
  "S18.1": "Give Us a King",
  "S19.1": "King Saul",
  "S111.1": "How Saul Saved Jabesh Gilead",
  "S112.1": "Samuel’s Warning",
  "S113.1": "Saul’s Unlawful Sacrifice",
  "S114.1": "Jonathan and his Armor Bearer Defeat the Philistines",
  "S115.1": "How Saul Lost the Kingdom",
  "S116.1": "Samuel Anoints David",
  "S116.14": "A Spirit Torments Saul",
  "S117.1": "David and Goliath",
  "S117.58": "Saul Becomes Jealous of David",
  "S118.17": "David and Michal",
  "S119.1": "David Flees Saul",
  "S120.1": "The Friendship of Jonathan and David",
  "S121.1": "David and the Showbread",
  "S122.1": "David’s Four Hundred Men",
  "S122.6": "Saul Kills the Priests",
  "S123.1": "The Battle at Keila",
  "S124.1": "David Spares Saul’s Life",
  "S125.1": "The Death of Samuel",
  "S125.2": "Abigail",
  "S126.1": "David Again Spares Saul’s Life",
  "S127.1": "David Serves the Philistines",
  "S128.3": "The Witch of En-Dor",
  "S129.1": "Why the Philistines Rejected David",
  "S130.1": "The Captivity of Ziklag",
  "S131.1": "The Death of Saul and his Sons",
  "S21.1": "David Mourns for Saul and Jonathan",
  "S22.1": "David King of Judah",
  "S22.8": "Ishbosheth King of Israel",
  "S22.12": "The War Between Israel and Judah",
  "S23.1": "Abner Joins David",
  "S23.22": "The Murder of Abner",
  "S24.1": "The Murder of Ishbosheth",
  "S25.1": "David Becomes King of all Israel",
  "S25.6": "How David Captured Jerusalem",
  "S25.17": "The Philistines Defeated",
  "S26.1": "Uzzah Touches the Ark of God",
  "S27.1": "God Makes a Covenant With David",
  "S29.1": "David Shows Kindness to Mephibosheth",
  "S210.1": "How Ammon Provoked David to War",
  "S211.1": "David, Bathsheba, and Uriah",
  "S212.1": "The Nathan the Prophet's Parable",
  "S212.24": "The Birth of Solomon",
  "S212.26": "The Capture of Rabbah",
  "S213.1": "Ammon’s Lust for Tamar",
  "S213.23": "Absalom Murders His Brothers",
  "S214.25": "David Forgives Absalom",
  "S215.1": "The Treason of Absalom",
  "S215.13": "David Escapes Jerusalem",
  "S216.1": "The Lies of Ziba and the Curses of Shimei",
  "S216.15": "The Council of Ahithophel",
  "S217.5": "The Council of Hushai",
  "S218.1": "The Death of Absalom",
  "S219.18": "How David Showed Mercy",
  "S219.40": "Israel Quarrels with Judah",
  "S220.1": "Sheba’s Rebellion",
  "S221.1": "Gibeon Avenged",
  "S221.15": "The Philistine Giants are Killed",
  "S222.1": "Praise for God’s Deliverance",
  "S223.1": "David’s Last Words",
  "S223.8": "David’s Mighty Men",
  "S224.1": "David’s Census",
  "S224.18": "The Angel and the Threshing Floor",
  "K11.1": "Adonijah Presumes the Crown",
  "K11.28": "Solomon Crowned King",
  "K12.12": "Adonijah Executed",
  "K12.26": "Abiathar Exiled, Joab Executed",
  "K12.36": "Shimei Executed",
  "K13.1": "Solomon Asks For Wisdom",
  "K14.1": "Solomon’s Administration",
  "K14.20": "Solomon’s Wisdom and Wealth",
  "K15.1": "Building the Temple",
  "K17.1": "Solomon the Builder",
  "K17.13": "Hiram the Craftsman",
  "K17.51": "The Temple is Completed",
  "K18.1": "The Ark is Brought Into the Temple",
  "K18.14": "Solomon’s Prayer",
  "K19.1": "God Appears to Solomon Again",
  "K110.1": "The Queen of Sheba",
  "K110.14": "The Wealth of Solomon",
  "K111.1": "Solomon’s Idolatry",
  "K111.14": "Solomon’s Enemies",
  "K111.26": "The Prophesy of Ahijah",
  "K112.1": "Rehoboam Divides Israel",
  "K112.25": "Jeroboam’s Golden Calves",
  "K113.1": "Jeroboam’s Hand Withers",
  "K113.11": "How the Prophet Was Killed by a Lion",
  "K114.1": "Abijah Prophesies Against Jeroboam",
  "K114.21": "The Reign of Rehoboam",
  "K115.1": "King Abijam of Judah",
  "K115.9": "King Asa of Judah",
  "K115.25": "King Nadab of Israel",
  "K115.33": "King Baasha of Israel",
  "K116.8": "King Elah of Israel",
  "K116.15": "King Zimri of Israel",
  "K116.21": "King Omri of Israel",
  "K117.29": "King Ahab of Israel",
  "K117.1": "Elijah Prophesies Drought",
  "K117.8": "The Widow of Zarephath",
  "K118.1": "Elijah Challenges Ahab",
  "K118.20": "The Lord Answers With Fire",
  "K118.41": "The Lord Sends Rain",
  "K119.1": "Elijah Flees Jezebel",
  "K119.9": "The Still Small Voice",
  "K119.19": "The Calling of Elisha",
  "K120.1": "Ahab’s War with Syria",
  "K120.30": "Ben-Hadad Released",
  "K121.1": "Naboth’s Vineyard",
  "K122.1": "Ahab and the False Prophets",
  "K122.29": "Ahab is Killed in Battle",
  "K122.41": "King Jehoshaphat of Judah",
  "K122.51": "King Ahaziah of Israel",
  "K21.1": "Elijah Denounces Ahaziah",
  "K22.1": "The Chariot of Fire",
  "K23.1": "Moab Rebels",
  "K24.1": "The Widow’ Oil",
  "K24.8": "The Shunammite Woman",
  "K24.18": "The Resurrection of the Shunammite’s Son",
  "K24.38": "The Deadly Stew",
  "K25.1": "Naaman is Cleansed of Leprosy",
  "K25.15": "The Greed of Gahazi",
  "K26.1": "The Axe Head is Recovered",
  "K26.8": "Horses and Chariots of Fire",
  "K26.24": "Ben-hadad Lays Siege to Samaria",
  "K27.1": "Elisha Promises Food",
  "K27.3": "The Leper’s Discovery",
  "K28.1": "The Shunammite's Land Restored",
  "K28.7": "Ben-Hadad is Murdered",
  "K28.16": "King Jehoram of Judah",
  "K28.25": "King Ahaziah of Judah",
  "K29.1": "Jehu is Anointed King of Israel",
  "K29.14": "Jehu Kills Joram and Ahaziah",
  "K29.30": "Jehu Kills Jezebel",
  "K210.1": "Jehu Kills Ahab’s Descendants",
  "K210.18": "Jehu Kills the Prophets of Baal",
  "K210.28": "King Jehu of Israel",
  "K211.1": "How Joash Overthrew Athaliah",
  "K211.21": "King Jehoash of Judah",
  "K212.4": "Jehoash Repairs the Temple",
  "K212.19": "The Death of Joash",
  "K213.1": "King Jehoahaz of Israel",
  "K213.10": "King Jehoash of Israel",
  "K213.14": "The Death of Elisha",
  "K214.1": "King Amaziah of Judah",
  "K214.22": "King Jeroboam II of Judah",
  "K215.1": "King Azariah of Judah",
  "K215.8": "King Zechariah of Israel",
  "K215.13": "King Shallum of Israel",
  "K215.17": "King Menahem of Israel",
  "K215.23": "King Pekahiah of Israel",
  "K215.27": "King Pekah of Israel",
  "K215.32": "King Jotham of Judah",
  "K216.1": "King Ahaz of Judah",
  "K217.6": "The Fall of Israel",
  "K217.24": "Assyria Resettles Samaria",
  "K218.1": "King Hezekiah of Judah",
  "K218.13": "Sennacherib’s Invades Judah",
  "K219.14": "The Prayer of Hezekiah",
  "K219.20": "Isaiah Foretells Sennacherib’s Fall",
  "K220.1": "Hezekiah’s Illness and Recovery",
  "K220.12": "The Babylonian Envoys",
  "K221.1": "King Manasseh of Judah",
  "K221.19": "King Amon of Judah",
  "K222.1": "King Josiah of Judah",
  "K222.8": "Hilkiah Finds the Book of the Law",
  "K223.1": "The Reforms of Josiah",
  "K223.28": "How Josiah Died in Battle",
  "K223.31": "Jehoahaz, The Captive King",
  "K223.36": "King Jehoiakim of Judah",
  "K224.8": "King Jehoiachin of Judah",
  "K224.10": "The Fall of Jerusalem",
  "K224.18": "King Zedekiah of Judah",
  "K225.1": "The Captivity of Judah",
  "K225.22": "Gedaliah Made Governor of Judah",
  "K225.27": "Jehoiachin Released",
  "R11.1": "From Adam to Abraham",
  "R11.28": "From Abraham to Jacob",
  "R12.1": "David's Genealogy",
  "R14.1": "The Descendants of Judah",
  "R14.24": "The Descendants of Simeon",
  "R15.1": "The Descendants of Rueben",
  "R15.11": "The Descendants of Gad",
  "R15.23": "The Half-Tribe of Manasseh",
  "R16.1": "The Descendants of Levi",
  "R17.1": "The Descendants of Issachar",
  "R17.6": "The Descendants of Benjamin",
  "R17.13": "The Descendants of Naphtali",
  "R17.14": "The Descendants of Manasseh",
  "R17.20": "The Descendants of Ephraim",
  "R17.30": "The Descendants of Asher",
  "R18.1": "Saul's Genealogy",
  "R19.1": "The Genealogy of the Returned Exiles",
  "R19.35": "Saul’s Genealogy Repeated",
  "R110.1": "How Saul and His Sons Died",
  "R111.1": "David is Anointed King",
  "R111.4": "How David Captured Jerusalem",
  "R111.10": "David’s Mighty Men",
  "R113.1": "How Uzzah Died",
  "R114.1": "David’s Family",
  "R114.8": "The Philistines are Defeated",
  "R115.1": "The Ark is Brought to Jerusalem",
  "R116.1": "The Tabernacle of David",
  "R116.8": "A Song of Thanks",
  "R117.1": "God’s Covenant with David",
  "R118.1": "David's Enemies Defeated",
  "R118.14": "David’s Administration",
  "R119.1": "The Ammonites Disgrace David’s Men",
  "R119.10": "The Defeat f Ammon and Syria",
  "R120.1": "The Siege of Rabbah",
  "R120.4": "The Philistine Giants are Killed",
  "R121.1": "David Numbers the People",
  "R121.18": "The Angel at the Threshing Floor",
  "R122.1": "Why David Couldn’t Build the Temple",
  "R123.1": "The Levite's Role",
  "R125.1": "Musicians for the Tabernacle",
  "R126.1": "Gatekeepers, Treasurers, and Other Officials",
  "R127.1": "The Israeli Army",
  "R127.16": "The Tribal Leaders",
  "R128.1": "David's Charge to Build the Temple",
  "R129.1": "Solomon is Anointed King",
  "R129.26": "The Death of David",
  "R21.1": "Worship at Gibeon",
  "R21.7": "Solomon Prays for Wisdom",
  "R21.14": "Solomon’s Great Wealth",
  "R22.1": "Preparing to Build the Temple",
  "R23.1": "Building the Temple",
  "R24.1": "Furnishing the Temple",
  "R25.2": "The Ark is Brought into the Temple",
  "R26.1": "Solomon Dedicates the Temple",
  "R27.1": "The Fire Falls",
  "R27.4": "A Great Sacrifice",
  "R27.11": "If my People",
  "R28.1": "Solomon’s Labors",
  "R29.1": "The Queen of Sheba",
  "R29.13": "The Wealth of Solomon",
  "R29.29": "The Death of Solomon",
  "R210.1": "Rehoboam Divides Israel",
  "R211.1": "Shemaiah Rebukes the Warmongers",
  "R211.13": "The Levites Flee Jeroboam",
  "R212.1": "The Egyptians Sack Jerusalem",
  "R213.1": "King Abijah of Judah",
  "R214.1": "King Asa of Judah",
  "R217.1": "King Jehoshaphat of Judah",
  "R218.1": "Jehoshaphat Allies with Ahab",
  "R218.28": "The Death of Ahab",
  "R219.1": "Jehoshaphat’s Reforms",
  "R220.1": "The Worshipers go to War",
  "R220.24": "How the Lord Delivered Judah",
  "R221.1": "King Jehoram of Judah",
  "R222.1": "King Ahaziah of Judah",
  "R222.10": "Queen Athaliah of Judah",
  "R223.1": "King Joash of Judah",
  "R223.16": "Jehoiada’s Reforms",
  "R224.1": "Joash Repairs the Temple",
  "R224.20": "Joash Kills the Prophet",
  "R224.23": "Joash is Assassinated",
  "R225.1": "King Amaziah of Judah",
  "R225.5": "Amaziah and the Mercenaries",
  "R225.17": "The Battle at Beth-shemesh",
  "R226.1": "King Uzziah of Judah",
  "R226.16": "Uzziah is Stricken with Leprosy",
  "R227.1": "King Jotham of Judah",
  "R228.1": "Judah Defeated",
  "R228.8": "The Prophet Rebukes the Captors",
  "R228.22": "The Idolatry of Ahaz",
  "R229.1": "King Hezekiah of Judah",
  "R229.3": "Hezekiah Consecrates the Temple",
  "R229.20": "Worship Resumes",
  "R230.1": "The Passover Observed",
  "R231.2": "The People Bring the Tithe and First Fruits",
  "R232.1": "Sennacherib Invades Judah",
  "R232.9": "The Blasphemies of Sennacherib",
  "R232.20": "The Angel Destroys Assyria’s Army",
  "R232.24": "Hezekiah’s Pride and Accomplishments",
  "R233.1": "King Manasseh of Judea",
  "R233.10": "Manasseh Repents",
  "R233.21": "King Amon of Judah",
  "R234.1": "King Josiah of Judah",
  "R234.8": "How Hilkiah Found the Book of the Law",
  "R234.22": "Huldah’s Prophesy",
  "R235.1": "Josiah Keeps the Passover",
  "R235.20": "Josiah is Killed in Battle",
  "R236.1": "Nico Disposes of Jehoahaz",
  "R236.5": "King Jehoiakim of Judah",
  "R236.9": "King Jehoiachin of Judah",
  "R236.11": "King Zedekiah of Judah",
  "R236.17": "Jerusalem Falls",
  "R236.22": "The Proclamation of Cyrus",
  "ER1.1": "The Proclamation of Cyrus",
  "ER2.1": "The Exiles who Returned",
  "ER3.1": "Rebuilding the Altar and Temple",
  "ER4.1": "The Temple’s Adversaries",
  "ER4.7": "The Adversaries Letter",
  "ER4.17": "Construction Ceases",
  "ER5.1": "Construction Resumes",
  "ER5.6": "Tattenai Writes to Darius",
  "ER6.1": "Cyrus’s Decree is Rediscovered",
  "ER6.6": "The Decree of Darius",
  "ER6.13": "The Finished Temple is Dedicated",
  "ER6.19": "The Passover Celebrated",
  "ER7.1": "Ezra Sent to Teach the People",
  "ER8.1": "The Genealogy of Those Who Returned with Ezra",
  "ER8.15": "Ezra Calls for the Levites",
  "ER8.21": "Fasting and Prayer for Safety",
  "ER9.1": "The Intermarriage Quandary",
  "ER10.1": "The People Repent",
  "NH1.1": "The Report From Jerusalem",
  "NH1.4": "Nehemiah’s Prayer",
  "NH2.1": "Nehemiah Returns to Judah",
  "NH3.1": "Rebuilding the Wall",
  "NH4.1": "Sanballat’s Opposition",
  "NH4.15": "The Work Resumes",
  "NH5.1": "Nehemiah Rebukes the Poor’s Oppressors",
  "NH5.14": "Nehemiah’s Frugality and Generosity",
  "NH6.1": "A Conspiracy Against Nehemiah",
  "NH6.13": "The Wall is Completed",
  "NH7.5": "The Exiles Who Returned",
  "NH8.1": "Ezra Reads the Law",
  "NH8.9": "This Day is Holy",
  "NH8.13": "Feasts of Booths Observed",
  "NH9.1": "The People Repent",
  "NH10.1": "The People Who Sealed the Covenant",
  "NH10.28": "The Obligation of the Covenant",
  "NH11.1": "The Leaders in Jerusalem",
  "NH11.25": "The Villages Outside Jerusalem",
  "NH12.1": "The Priests and Levites",
  "NH12.27": "The Wall is Dedicated",
  "NH13.1": "The Reforms of Nehemiah",
  "ET1.1": "The Feast of King Ahasuerus",
  "ET1.10": "Queen Vashti’s Refusal",
  "ET2.1": "Esther is Made Queen",
  "ET2.19": "Mordecai Foils an Assassination",
  "ET3.1": "Haman Plots Genocide",
  "ET4.1": "Esther Calls a Fast",
  "ET5.1": "Esther’s Banquet",
  "ET5.9": "Haman’s Plan to Hang Mordecai",
  "ET6.1": "The King Honors Mordecai",
  "ET7.1": "Esther Accuses Haman",
  "ET7.7": "Haman is Hung",
  "ET8.1": "How Esther Saved the Jews",
  "ET9.1": "The Jews Destroy Their Enemies",
  "ET9.20": "The Feast of Purim",
  "ET10.1": "Mordecai is Promoted",
  "JB1.1": "Job's Integrity and Prosperity",
  "JB1.6": "Satan Before the Lord",
  "JB1.13": "Job Loses his Children and Wealth",
  "JB2.1": "Job Loses His Health",
  "JB2.11": "Eliphaz, Bildad, and Zophar",
  "JB3.1": "Job Curses the Day He was Born",
  "JB4.1": "Eliphaz Speaks, The Prosperity of the Innocent",
  "JB6.1": "Job’s Replies, My Cause is Just",
  "JB8.1": "Bildad Speaks, The Importance of Repentance",
  "JB9.1": "Job Replies, How Can a Man be Right Before God",
  "JB11.1": "Zophar Speaks, The Omniscience of God",
  "JB12.1": "Job Replies, The Lord Has Done This",
  "JB14.1": "Death is Impending",
  "JB15.1": "Eliphaz Speaks, The Fear of the Lord",
  "JB16.1": "Job Replies, You Are Miserable Comforters",
  "JB17.1": "Where Then Is My Hope",
  "JB18.1": "Bildad Speaks, The Light of the Wicked is Put Out",
  "JB19.1": "Job Replies, For I Know That My Redeemer Lives",
  "JB20.1": "Zophar Speaks, The Exulting of the Wicked is Short",
  "JB21.1": "Job Replies, Why Do the Wicked Live?",
  "JB22.22": "Eliphaz Speaks, There is No End to Your Iniquities",
  "JB23.1": "Job Replies, Where is God?",
  "JB25.1": "Bildad Speaks, Men are Maggots",
  "JB26.1": "Job Replies, God’s Majesty is Unsearchable",
  "JB27.1": "I Hold Fast My Righteousness",
  "JB28.1": "Where Shall Wisdom be Found",
  "JB31.1": "Job Maintains His Innocence",
  "JB32.1": "Elihu’s Rebuke",
  "JB34.1": "The Justice and Greatness of God",
  "JB38.1": "The Lord Answers Job",
  "JB39.1": "From Mountain Goats to Eagles",
  "JB40.1": "Job Promises to be Silent",
  "JB40.6": "The Lord Answers Out of the Whirlwind",
  "JB40.15": "Behemoth and Leviathan",
  "JB42.1": "Job Repents",
  "JB42.7": "God Rebukes Job’s Friends",
  "JB42.10": "Job’s Fortune Restored",
  "PS1.1": "Blessed is the Man",
  "PS2.1": "Why Do the Nations Rage",
  "PS3.1": "Save Me, O my God",
  "PS4.1": "Put Your Trust in the Lord",
  "PS5.1": "Lead me, O Lord, In Your Righteousness",
  "PS6.1": "Turn, O Lord, Deliver My Life",
  "PS7.1": "God is a Righteous Judge",
  "PS8.1": "How Majestic is Your Name in All the Earth",
  "PS9.1": "The Lord Sits Enthroned Forever",
  "PS10.1": "Why Do You Hide Yourself",
  "PS11.1": "The Lord is in His Holy Temple",
  "PS12.1": "The Words of the Lord are Pure Words",
  "PS13.1": "How Long , Oh Lord?",
  "PS14.1": "The Fool Says in His Heart There is no God",
  "PS15.1": "Who Shall Dwell On Your Holy Hill",
  "PS16.1": "Fullness of Joy and Pleasures Forever",
  "PS17.1": "Attend My Cry",
  "PS18.1": "The Lord is my Rock",
  "PS19.1": "The Heavens Declare the Glory of God",
  "PS20.1": "May the Lord Answer You",
  "PS21.1": "We Will Sing and Praise Your Power",
  "PS22.1": "Why Have You Forsaken Me",
  "PS23.1": "The Lord is My Shepherd",
  "PS24.1": "The Earth is The Lord’s",
  "PS25.1": "O my God, I Trust in Thee",
  "PS26.1": "Test Me Oh Lord and Know My Heart",
  "PS27.1": "The Lord is My Light and My Salvation",
  "PS28.1": "The Lord is My Strength and My Shield",
  "PS29.1": "Ascribe to the Lord Glory",
  "PS30.1": "But Joy Comes In the Morning",
  "PS31.1": "Into Your Hands I Commit My Spirit",
  "PS32.1": "Be Glad In the Lord and Rejoice",
  "PS33.1": "Blessed is the Nations Whose God is the Lord",
  "PS34.1": "O Taste and See that the Lord is Good",
  "PS35.1": "Great is the Lord",
  "PS36.1": "Your Faithfulness Reaches to the Clouds",
  "PS37.1": "Delight Yourself In the World",
  "PS38.1": "Rebuke Me Not In Your Anger",
  "PS39.1": "My Hope Is In You",
  "PS40.1": "I Waited Patiently For the Lord",
  "PS41.1": "Blessed Is He that Considers the Poor",
  "PS42.1": "As the Deer Pants for the Water",
  "PS43.1": "Send Out Your Light and Your Truth",
  "PS44.1": "Redeem Us",
  "PS45.1": "Your Throne, O God, Is Forever",
  "PS46.1": "God Is Our Refuge and Strength",
  "PS47.1": "Clap Your Hands",
  "PS48.1": "Mount Zion On the Sides of the North",
  "PS49.1": "God Will Redeem My Soul",
  "PS50.1": "Our God Comes",
  "PS51.1": "The Multitude of Your Mercies",
  "PS52.1": "The Goodness of God Endures Continually",
  "PS53.1": "There is None Who Does Good",
  "PS54.1": "Judge by Your Strength",
  "PS55.1": "He Will Sustain You",
  "PS56.1": "You Have Put My Tears in Your Bottle",
  "PS57.1": "Let Your Glory Be All Over the Earth",
  "PS58.1": "Do You Judge Uprightly?",
  "PS59.1": "The Heathen in Derision",
  "PS60.1": "Through God We Shall Do Valiantly",
  "PS61.1": "A Strong Tower",
  "PS62.": "01I Shall Not Be Greatly Moved",
  "PS63.1": "Early Will I Seek You",
  "PS64.1": "The Righteous Will Be Glad",
  "PS65.1": "The Goodness of Your House",
  "PS66.1": "Make a Joyful Noise",
  "PS67.1": "Shine Upon Us",
  "PS68.1": "Let God Arise",
  "PS69.1": "For the Zeal of Your House",
  "PS70.1": "Oh Lord Do Not Delay",
  "PS71.1": "Do Not Forsake Me",
  "PS72.1": "He Will Deliver the Needy",
  "PS73.1": "Truly God is Good",
  "PS74.1": "You Have Cast Us Off",
  "PS75.1": "All the Horns of the Wicked",
  "PS76.1": "In Judah God is Known",
  "PS77.1": "I Will Remember the Deeds of the Lord",
  "PS78.1": "I Will Open My Mouth in a Parable",
  "PS79.1": "Pour Out Your Wrath",
  "PS80.1": "A Vine Out of Egypt",
  "PS81.1": "O That My People Would Listen to Me",
  "PS82.1": "Ye are Gods",
  "PS83.1": "Let Them be Confounded",
  "PS84.1": "My Soul Longs and Even Faints",
  "PS85.1": "Grant Us Your Salvation",
  "PS86.1": "Incline Your Ear",
  "PS87.1": "This Man Was Born There",
  "PS88.1": "Down to the Pit",
  "PS89.1": "I Will Establish Your Seed Forever",
  "PS90.1": "Our Dwelling Place",
  "PS91.1": "The Secret Place of the Most High",
  "PS92.1": "To Give Thanks",
  "PS93.1": "He is Clothed in Majesty",
  "PS94.1": "Judge of the Earth",
  "PS95.1": "We are the People of His Pasture",
  "PS96.1": "Sing Unto the Lord a New Song",
  "PS97.1": "The Lord Reigns, Let the Earth Rejoice",
  "PS98.1": "He Has Done Great Things",
  "PS99.1": "He Sits Between the Cherubim",
  "PS100.1": "Enter His Gates with Thanksgiving",
  "PS101.1": "I Will Set No Wicked Thing Before My Eyes",
  "PS102.1": "Your Years Have No End",
  "PS103.1": "Bless His Holy Name",
  "PS104.1": "O Lord How Manifold are Your Works",
  "PS105.1": "Make Known His Deeds",
  "PS106.1": "For He is Good and His Mercy Endures",
  "PS107.1": "Let the Redeemed of the Lord Say So",
  "PS108.1": "Your Truth Reaches the Clouds",
  "PS109.1": "I Give Myself to Prayer",
  "PS110.1": "Sit at My Right Hand",
  "PS111.1": "Blessed is the Man that Fears the Lord",
  "PS112.1": "An Everlasting Remembrance",
  "PS113.1": "From the Rising of the Sun",
  "PS114.1": "What Ailed You, O Sea?",
  "PS115.1": "But Unto Your Name Give Glory",
  "PS116.1": "Our God is Merciful",
  "PS117.1": "The Truth of the Lord Endures",
  "PS118.1": "The Stone Which the Builders Rejected",
  "PS119.1": "Blessed are the Undefiled",
  "PS119.9": "Thy Word Have I Hid In My Heart",
  "PS119.17": "Open My Eyes",
  "PS119.25": "My Soul Cleaves to the Dust",
  "PS119.33": "The Way of Your Statutes",
  "PS119.41": "I Trust In Your Word",
  "PS119.49": "I Have Remembered Your Name",
  "PS119.57": "You are My Portion",
  "PS119.65": "That I Might Learn Your Statutes",
  "PS119.73": "Your Hands Have Made Me",
  "PS119.81": "I Hope In Your Word",
  "PS119.89": "I am Yours, Save Me",
  "PS119.97": "O How I Love Your Law",
  "PS119.105": "A Lamp to My Feet",
  "PS119.113": "I Hate Vain Thoughts",
  "PS119.121": "I Hate Every False Way",
  "PS119.129": "Your Testimonies are Wonderful",
  "PS119.137": "Your Word is Very Pure",
  "PS119.145": "The Night Watches",
  "PS119.153": "Plead My Cause",
  "PS119.161": "Seven Times a Day, I Praise You",
  "PS119.169": "Let My Soul Live",
  "PS120.1": "I Am For Peace",
  "PS121.1": "I Will Lift Up My Eyes to the Hills",
  "PS122.1": "Let Us Go Into the House of the Lord",
  "PS123.1": "Unto You I Lift My Eyes",
  "PS124.1": "If it Had Not Been the Lord",
  "PS125.1": "They That Trust In the Lord",
  "PS126.1": "Bringing in the Sheaves",
  "PS127.1": "Except the Lord Build the House",
  "PS128.1": "It Will Be Well With You",
  "PS129.1": "They Afflicted Me from My Youth",
  "PS130.1": "But There Is Forgiveness",
  "PS131.1": "My Soul is Like a Weaned Child",
  "PS132.1": "A Habitation of the Mighty God",
  "PS133.1": "For Brethren to Dwell Together In Unity",
  "PS134.1": "Lift Up Your Hands in the Sanctuary",
  "PS135.1": "The Lord Has Chosen Jacob",
  "PS136.1": "His Mercy Endures Forever",
  "PS137.1": "By the Rivers of Babylon",
  "PS138.1": "I Will Praise You with My Whole Heart",
  "PS139.1": "You are Acquainted With All My Ways",
  "PS140.1": "The Upright Will Dwell in Your Presence",
  "PS141.1": "Keep the Door of My Lips",
  "PS142.1": "Bring My Soul Out of Prison",
  "PS143.1": "The Land of Uprightness",
  "PS144.1": "Who Teaches My Hands to War",
  "PS145.1": "The Lord is Good to All",
  "PS146.1": "While I Live I Will Praise the Lord",
  "PS147.1": "He Heals the Broken Heart",
  "PS148.1": "The Lord Builds up Jerusalem",
  "PS149.1": "Let Israel Rejoice In Him That Made Him",
  "PS150.1": "Praise Ye the Lord",
  "PR1.1": "The Fear of the Lord",
  "PR1.8": "If Sinners Entice You",
  "PR1.20": "Wisdom Cries Aloud",
  "PR2.1": "For the Lord Gives Wisdom",
  "PR3.1": "Trust in the Lord with All Your Heart",
  "PR3.13": "Blessed is the One Who Finds Wisdom",
  "PR4.1": "A Father’s Instruction",
  "PR5.1": "The Path to Sheol",
  "PR6.1": "Warnings",
  "PR6.20": "The Adulteress",
  "PR8.1": "Does Not Wisdom Call?",
  "PR9.1": "Wisdom’s Feast",
  "PR9.13": "The Call of Folly",
  "PR10.1": "The Proverbs of Solomon",
  "PR30.1": "The Sayings of Agur",
  "PR31.1": "The Sayings of King Lemuel",
  "EC1.1": "Vanity of Vanities",
  "EC1.12": "Wisdom is Vanity",
  "EC2.1": "Pleasure is Vanity",
  "EC2.18": "Labor is Vanity",
  "EC3.1": "A Time for Everything",
  "EC3.9": "What Gain Has the Worker?",
  "EC3.16": "To Dust all Return",
  "EC4.1": "The Oppression Under the Sun",
  "EC5.1": "Fear God",
  "EC5.8": "Wealth and Honor are Vanity",
  "EC7.1": "Wisdom and Folly",
  "EC8.1": "Obey the King",
  "EC9.1": "The Certainty of Death",
  "EC9.7": "Enjoy Life",
  "EC10.11": "The Poor Man’s Wisdom",
  "EC11.1": "Cast Your Bread on the Waters",
  "EC12.1": "Remember Your Creator",
  "IS1.1": "The Rebellious Children",
  "IS1.21": "The Faithful City has Become a Whore",
  "IS2.1": "The Mountain of the House of the Lord",
  "IS2.6": "The Day of the Lord",
  "IS3.1": "Judah and Jerusalem are Judged",
  "IS4.1": "The Branch of the Lord",
  "IS5.1": "The Lord’s Vineyard",
  "IS6.1": "I Saw the Lord",
  "IS7.1": "Isaiah’s Prophesy to Ahaz",
  "IS7.10": "And Will Call His Name Immanuel",
  "IS8.1": "The Assyrian Invasion is Prophesied",
  "IS8.11": "Wait for the Lord, Let Him be Your Fear",
  "IS9.1": "For Unto Us a Child is Born",
  "IS9.8": "The Arrogant and the Oppressor are Judged",
  "IS10.5": "The Assyrians are Judged",
  "IS11.1": "The Righteous Branch",
  "IS12.1": "The Lord is My Strength and My Song",
  "IS13.1": "Babylon is Judged",
  "IS14.1": "For the Lord Will Have Compassion",
  "IS14.3": "A Taunt for Babylon",
  "IS14.24": "I Will Break the Assyria",
  "IS14.28": "Rejoice Not, O Philistia",
  "IS15.1": "An Oracle Concerning Moab",
  "IS17.1": "An Oracle Concerning Damascus",
  "IS18.1": "An Oracle Concerning Cush",
  "IS19.1": "An Oracle Concerning Egypt",
  "IS20.1": "A Portent Against Egypt and Cush",
  "IS21.1": "Fallen, Fallen is Babylon",
  "IS22.1": "An Oracle Concerning Jerusalem",
  "IS23.1": "An Oracle Concerning Tyre and Sidon",
  "IS24.1": "The Lord Will Empty the Earth",
  "IS25.1": "He Will Swallow Up Death in Victory",
  "IS26.1": "You Will Keep Him in Perfect Peace",
  "IS27.1": "How Israel Will be Restored",
  "IS28.1": "The Judgment Upon Ephraim and Jerusalem",
  "IS28.14": "The Cornerstone",
  "IS29.1": "The Siege of Jerusalem",
  "IS30.1": "Egypt’s Help is Worthless",
  "IS30.18": "The Lord Waits to be Gracious",
  "IS31.1": "Woe to Those Who Go Down to Egypt",
  "IS32.1": "A King Will Reign",
  "IS32.9": "Rise Up, You Women",
  "IS33.1": "He Will Fill Zion with Justice",
  "IS34.1": "The Lord’s Rage Against the Nations",
  "IS35.1": "Strengthen the Weak Hands",
  "IS36.1": "Sennacherib Invades",
  "IS37.1": "Hezekiah Consults Isaiah",
  "IS37.14": "The Prayer of Hezekiah",
  "IS37.21": "How Sennacherib Fell",
  "IS38.1": "Hezekiah and the Cake of Figs",
  "IS39.1": "The Babylonian Ambassadors",
  "IS40.1": "Comfort, Comfort My People",
  "IS41.1": "Fear Not For I am With You",
  "IS42.1": "A Bruised Reed He Will Not Break",
  "IS42.18": "Hear You Deaf, and Look, You Blind",
  "IS43.1": "Bring My Sons From Afar",
  "IS44.1": "Water on the Thirsty Land",
  "IS44.6": "I Am the First and I Am the Last",
  "IS44.9": "The Folly of Idolatry",
  "IS44.21": "The Lord Redeems Israel",
  "IS45.1": "Cyrus, The Lord’s Anointed",
  "IS46.1": "Idols and the One True God",
  "IS47.1": "Babylon Humiliated",
  "IS48.1": "Israel’s Obstinance",
  "IS49.1": "You are My Servant Israel",
  "IS50.1": "Is My Hand Shortened that it Cannot Save?",
  "IS50.7": "I Have Set My Face Like a Flint",
  "IS51.1": "The Lord Comforts Zion",
  "IS52.1": "The Feet of Him Who Brings Good News",
  "IS53.1": "By His Stripes We are Healed",
  "IS54.1": "The Covenant of Peace",
  "IS55.1": "Come to the Waters",
  "IS55.6": "Seek the Lord While He May be Found",
  "IS56.1": "Hope for Eunuchs and Foreigners",
  "IS57.1": "The Idolaters Accused",
  "IS57.14": "The Contrite and the Lowly",
  "IS58.1": "The Lord’s Chosen Fast",
  "IS59.1": "Your Sins Have Hidden His Face",
  "IS60.1": "But the Lord Will Arise",
  "IS61.1": "The Year of the Lord’s Favor",
  "IS62.1": "I Have Set Watchmen On Your Walls",
  "IS63.1": "Like Him Who Treads the Winepress",
  "IS63.7": "Remembering the Lord’s Mercy",
  "IS64.1": "Righteousness as Filthy Rags",
  "IS65.1": "I Have spread Out My Hands All the Day",
  "IS65.17": "New Heavens and a New Earth",
  "IS66.1": "He Who is Humble and Contrite in Spirit",
  "JR1.1": "The Lord Speaks to Jeremiah",
  "JR2.1": "Israel Has Forsaken the Lord",
  "JR3.6": "Return to Me",
  "JR4.5": "I Bring Disaster from the North",
  "JR4.19": "The Lord’s Anguish over Judah",
  "JR5.1": "Jerusalem Refuses to Repent",
  "JR5.14": "The Lord Brings Invasion",
  "JR6.1": "The Coming Destruction",
  "JR7.1": "The Temple of the Lord",
  "JR7.30": "The Valley of Slaughter",
  "JR8.1": "Everyone Deals Falsely",
  "JR8.18": "Is There No Balm in Gilead?",
  "JR10.1": "Of Idols and the Living God",
  "JR11.1": "They Have Broken My Covenant",
  "JR12.1": "Why Do the Wicked Prosper",
  "JR13.1": "The Ruined Girdle",
  "JR13.12": "The Jars of Wine",
  "JR14.1": "Famine, Sword, and Pestilence",
  "JR15.1": "The Lord Appoints Destruction",
  "JR15.10": "The Grief of Jeremiah",
  "JR16.1": "Famine, Sword, and Death",
  "JR17.1": "Cursed is the Man Who Trusts in Man",
  "JR17.17": "Heal Me",
  "JR18.1": "The Potter’s House",
  "JR19.1": "The Broken Bottle",
  "JR20.1": "How Pasher Persecuted Jeremiah",
  "JR21.1": "Nebuchadnezzar is Coming",
  "JR22.1": "The Judgment Against Josiah’s Sons",
  "JR23.1": "A Righteous Branch",
  "JR23.9": "The False Prophets",
  "JR24.1": "The Parable of the Figs",
  "JR25.1": "The Cup of the Lord’s Wrath",
  "JR26.1": "Jeremiah’s Life is Spared",
  "JR27.1": "The Sign of the Yoke",
  "JR28.1": "Hananiah the False Prophet",
  "JR29.1": "A Letter to the Exiles",
  "JR29.24": "Shemaiah the False Prophet",
  "JR30.1": "I Will Restore the Fortunes of My People",
  "JR31.1": "An Everlasting Love",
  "JR31.31": "A New Covenant",
  "JR32.1": "Jeremiah Buys a Field",
  "JR32.16": "Nothing is Too Difficult for You",
  "JR33.1": "The Promise of Peace",
  "JR34.1": "How Zedekiah Will Die",
  "JR35.1": "The Obedience of the Rechabites",
  "JR36.1": "Jehoiakim Burns Jeremiah’s Scroll",
  "JR37.1": "A Warning for Zedekiah",
  "JR37.11": "Jeremiah Imprisoned",
  "JR38.1": "Thrown Down a Well",
  "JR39.1": "Jerusalem Falls",
  "JR39.11": "Jeremiah Delivered",
  "JR40.1": "Jeremiah Stays Behind",
  "JR41.1": "The Murder of Gedaliah",
  "JR42.1": "Do Not Go to Egypt",
  "JR43.1": "Jeremiah in Egypt",
  "JR44.1": "The Judgment for Idolatry",
  "JR45.1": "A Message for Baruch",
  "JR46.1": "Egypt’s Coming Destruction",
  "JR47.1": "The Judgment of Philistia",
  "JR48.1": "The Judgment of Moab",
  "JR49.1": "The Judgment of Ammon",
  "JR49.7": "The Judgment of Edom",
  "JR49.23": "The Judgment of Damascus",
  "JR49.28": "The Judgment of Kedar and Hazor",
  "JR49.34": "The Judgment of Elam",
  "JR50.1": "The Judgment of Babylon",
  "JR52.1": "How Jerusalem Fell",
  "LM1.1": "How Lonely Sits the City",
  "LM2.1": "The Lord has Become Like an Enemy",
  "LM3.1": "Great Is Your Faithfulness",
  "LM4.16": "The lord Himself Has Scattered Them",
  "LM5.1": "Restore Us to Yourself",
  "EK1.4": "The Glory of the Lord",
  "EK2.1": "The Calling of Ezekiel",
  "EK3.16": "I Have Made You a Watchman",
  "EK4.1": "A Model of the Siege",
  "EK5.1": "Ezekiel Shaves His Head",
  "EK6.1": "Judgment Against Idolatry",
  "EK7.1": "An End Has Come",
  "EK8.1": "Abominations in the Temple",
  "EK9.1": "The Idolaters are Executed",
  "EK10.1": "The Glory Departs",
  "EK11.1": "The Twenty Five Wicked Counselors",
  "EK11.14": "One Heart and a New Spirit",
  "EK12.1": "A Symbolic Exile",
  "EK13.1": "The False Prophets are Condemned",
  "EK14.1": "Turn Away From Your Idols",
  "EK15.1": "A Useless Vine",
  "EK16.1": "A Faithless Bride",
  "EK17.1": "Two Eagles and a Vine",
  "EK18.1": "The Soul Who Sins Shall Die",
  "EK19.1": "A Lament for the Princes",
  "EK20.1": "A History of Rebellion",
  "EK21.1": "The Lord Has Drawn His Sword",
  "EK22.1": "Judge the Bloody City",
  "EK23.1": "Ohola and Oholibah",
  "EK24.1": "The Siege of Jerusalem",
  "EK24.15": "Ezekiel’s Wife Dies",
  "EK25.1": "A Prophecy Against Ammon",
  "EK25.8": "A Prophesy Against Moab and Seir",
  "EK25.12": "A Prophesy Against Edom",
  "EK25.15": "A Prophesy Against Philistia",
  "EK26.1": "A Prophesy Against Tyre",
  "EK27.1": "A Lament for Tyre",
  "EK28.1": "The Proud Prince of Tyre",
  "EK28.11": "The Cherub King of Tyre",
  "EK28.20": "The Prophesy Against Sidon",
  "EK29.1": "A Prophesy Against Egypt",
  "EK30.1": "A Sword Shall Come Upon Egypt",
  "EK31.1": "How Pharaoh Will Die",
  "EK33.1": "A Watchman for the House of Israel",
  "EK33.21": "The City Has Been Struck Down",
  "EK34.1": "Should Not Shepherds Feed the Sheep",
  "EK34.25": "A Covenant of Peace",
  "EK35.1": "A Prophesy Against Mount Seir",
  "EK36.1": "The Mountains of Israel are Blessed",
  "EK36.16": "The Lord’s Concern for His Holy Name",
  "EK36.22": "I Will Give You a New Heart",
  "EK37.1": "The Valley of Dry Bones",
  "EK38.1": "The Prophesy Against Gog",
  "EK40.1": "A New Temple",
  "EK41.1": "The Inner Temple",
  "EK42.1": "The Temple’s Chambers",
  "EK43.1": "The Glory of the Lord Fills the Temple",
  "EK44.15": "I Am Your Portion",
  "EK45.1": "The Holy Portion",
  "EK45.7": "The Prince’s Portion",
  "EK46.1": "The Prince and His Offerings",
  "EK47.1": "The Water Flows From the Temple",
  "EK47.13": "The Division of the Land",
  "EK48.30": "The Gates of the City",
  "DN1.1": "Why Daniel Was Taken to Babylon",
  "DN1.8": "Daniel’s Diet",
  "DN2.1": "Nebuchadnezzar’s Dream",
  "DN2.31": "Daniel Interprets the Dream",
  "DN3.1": "The Statue",
  "DN3.8": "The Fiery Furnace",
  "DN4.5": "Nebuchadnezzar’s Second Dream",
  "DN4.28": "The Humiliation and Restoration of Nebuchadnezzar",
  "DN5.1": "Mene, Mene, Tekel, Parsin",
  "DN6.1": "The Lion’s Den",
  "DN7.1": "The Four Beasts",
  "DN7.9": "The Ancient of Days and the Son of Man",
  "DN8.1": "The Ram and the Goat",
  "DN9.1": "A Prayer for Israel",
  "DN9.20": "Gabriel Brings Understanding",
  "DN9.24": "The Seventy Weeks",
  "DN10.1": "The Vision of a Man",
  "DN11.1": "The Kings of the North and the Kings of the South",
  "DN12.1": "The End of the Days",
  "HS1.1": "A Wife of Whoredom",
  "HS2.1": "Israel is an Unfaithful Wife",
  "HS2.14": "The Lord Woos Her in the Desert",
  "HS3.1": "How Hosea Redeemed His Wife",
  "HS4.1": "The Lord’s Controversy",
  "HS5.1": "The Coming Wrath",
  "HS6.1": "He Has Torn Us, That He May Heal Us",
  "HS8.1": "Reap the Whirlwind",
  "HS9.1": "The Days of Punishment Have Come",
  "HS11.1": "How Can I Give You Up",
  "HS12.2": "The Lord's Indictment",
  "HS13.1": "I Will Devour Them",
  "HS14.1": "Return, O Israel",
  "JL1.1": "The Locust Invasion",
  "JL1.13": "Consecrate a Fast",
  "JL2.1": "The Day of the Lord",
  "JL2.12": "Return to Me",
  "JL2.18": "The Lord has Pity",
  "JL2.28": "I Will Pour Out My Spirit",
  "JL3.1": "The Oppressors are Judged",
  "JL3.17": "Jerusalem Shall be Holy",
  "AM1.2": "For Three Transgressions",
  "AM3.1": "Who Can But Prophesy",
  "AM4.1": "The Days are Coming Upon You",
  "AM5.1": "Seek Me and Live",
  "AM6.1": "Woe to Those Who are at Ease",
  "AM7.1": "O Lord God, Please Cease",
  "AM7.10": "How Amaziah Came Against Amos",
  "AM8.1": "The End Has Come",
  "AM9.1": "Israel Destroyed and Restored",
  "OB1.1": "A Prophesy Against Edom",
  "OB1.15": "The Day of the Lord is Near",
  "JH1.1": "Jonah Flees the Presence of the Lord",
  "JH1.7": "How Jonah was Swallowed by a Whale",
  "JH2.1": "The Prayer of Jonah",
  "JH3.1": "Jonah in Nineveh",
  "JH4.1": "The Plant and the Worm",
  "MC1.1": "The Lord Will Tread Upon the High Places",
  "MC2.1": "Woe to the Wicked",
  "MC3.1": "The Lying Leaders of Israel",
  "MC4.1": "The Mountain of the Lord",
  "MC5.1": "O, Bethlehem",
  "MC6.1": "How Have I Wearied You",
  "MC6.6": "What Does the Lord Require",
  "MC7.1": "The God of My Salvation",
  "NM1.1": "An Oracle Concerning Nineveh",
  "NM3.1": "Woe to the Bloody City",
  "HK1.1": "Habakkuk Complains",
  "HK1.5": "The Lord Answers",
  "HK1.12": "We Shall Not Die",
  "HK2.2": "Write the Vision",
  "HK2.6": "Woes to the Wicked",
  "HK3.1": "The Prayer of Habakkuk",
  "ZP1.1": "The End of all Things",
  "ZP1.7": "The Day of the Lord is Near",
  "ZP2.1": "O Shameless Nation",
  "ZP3.1": "The Oppressing City",
  "ZP3.9": "A Pure Speech",
  "ZP3.14": "Rejoice and Exult With All Your Heart",
  "HG1.1": "Rebuilding the Temple",
  "HG2.10": "The Unclean Offerings",
  "HG2.20": "Zerubbabel the Signet Ring",
  "ZC1.1": "Do Not Be Like Your Fathers",
  "ZC1.7": "The Vision of a Horseman",
  "ZC1.18": "The Vision of the Scattered Horns and the FourCraftsmen",
  "ZC2.1": "The Vision of the Man With a Measuring Line",
  "ZC3.1": "The Vision of Joshua the High Priest",
  "ZC4.1": "The Vision of the Golden Lamp Stand",
  "ZC5.1": "The Vision of the Flying Scroll",
  "ZC5.5": "The Vision of the Woman in a Basket",
  "ZC6.1": "The Vision of the Chariots",
  "ZC6.9": "The Vision of the Crown and Temple",
  "ZC7.1": "True Judgments, Kindness, and Mercy",
  "ZC8.1": "I Will Save My People",
  "ZC9.1": "The Lord Has an Eye On Mankind",
  "ZC9.9": "Behold Your King is Coming",
  "ZC10.1": "Rain In the Time of the Later Rain",
  "ZC11.1": "Woe to My Worthless Shepherd",
  "ZC12.1": "The Sign of the Blind Horses",
  "ZC12.10": "Him Who They Have Pierced",
  "ZC13.1": "Idolatry Destroyed",
  "ZC13.7": "Strike the Shepherd",
  "ZC14.1": "Holy to the Lord",
  "ML1.1": "The Lord Loves Israel",
  "ML1.6": "A Polluted Offering",
  "ML2.1": "A Warning for the Priests",
  "ML3.1": "Jon the Baptist Foretold",
  "ML3.6": "The Tithe",
  "ML3.16": "The Book of Remembrance",
  "ML4.1": "The Great Day of the Lord",
  "MT1.1": "The Genealogy of Jesus Christ",
  "MT1.18": "The Birth of Jesus",
  "MT2.1": "Wise Men From the East",
  "MT2.13": "The Flight to Egypt",
  "MT2.16": "Massacre in Bethlehem",
  "MT2.22": "The Return to Nazareth",
  "MT3.1": "John the Baptist",
  "MT3.13": "The Baptism of Jesus",
  "MT4.1": "Jesus is Tempted by the Devil",
  "MT4.18": "Jesus Calls His First Disciples",
  "MT5.1": "The Sermon On the Mount",
  "MT5.2": "The Beatitudes",
  "MT5.13": "The Salt and the Light",
  "MT5.17": "Christ Fulfills the Law",
  "MT5.21": "Anger",
  "MT5.27": "Lust",
  "MT5.31": "Divorce",
  "MT5.33": "Swearing",
  "MT5.38": "Revenge",
  "MT6.1": "Exhibition",
  "MT6.5": "The Lord's Prayer",
  "MT6.16": "Fasting",
  "MT6.19": "Treasure in Heaven",
  "MT6.25": "Worry",
  "MT7.1": "Judging Others",
  "MT7.7": "Ask and It Will Be Given to You",
  "MT7.12": "The Golden Rule",
  "MT7.15": "By Their Fruits",
  "MT7.24": "A House On the Rock",
  "MT8.1": "A Leper Cleansed",
  "MT8.5": "A Centurion's Faith",
  "MT8.18": "The Cost of Discipleship",
  "MT8.23": "Jesus Calms the Storm",
  "MT8.28": "Two Demon Possessed Men are Delivered",
  "MT9.1": "A Paralytic Healed",
  "MT9.9": "Matthew the Tax Collector",
  "MT9.14": "Why the Disciples Didn’t Fast",
  "MT9.18": "A Woman Healed and a Girl Resurrected",
  "MT9.27": "Two Blind Men are Healed",
  "MT9.32": "A Mute Healed",
  "MT9.35": "The Harvest is Plentiful",
  "MT10.1": "The Twelve Apostles",
  "MT10.16": "Sheep In the Midst of Wolves",
  "MT10.34": "A Controversial Gospel",
  "MT10.40": "Hospitality",
  "MT11.1": "A Message From Jon the Baptist",
  "MT11.20": "Woe to You Chorazin, Woe to You Bethsaida",
  "MT11.25": "Come to Me All Who Labor and are Heavy Laden",
  "MT12.1": "Lord of the Sabbath",
  "MT12.9": "The Withered Hand Restored",
  "MT12.18": "Justice to the Gentiles",
  "MT12.22": "Blasphemy Against the Holy Spirit",
  "MT12.33": "A Tree is Known By it's Fruit",
  "MT12.38": "Jonah, Nineveh, and the Queen of the South",
  "MT12.43": "The Unclean Spirit Returns",
  "MT12.46": "Who Is My Mother and Who Are My Brothers?",
  "MT13.1": "The Parable of the Sower",
  "MT13.31": "Leven and a Grain of Mustard Seed",
  "MT13.44": "The Hidden Treasure",
  "MT13.47": "A Net That Was Thrown Into the Sea",
  "MT13.53": "Nazareth Dishonors Jesus",
  "MT14.1": "How Jon the Baptist Died",
  "MT14.13": "The Feeding of the Five Thousand",
  "MT14.22": "Jesus Walks on Water",
  "MT14.34": "The Healings in Gennesaret",
  "MT15.1": "Their Hearts are Far from Me",
  "MT15.10": "What Defiles a Person",
  "MT15.21": "The Crumbs that Fall From the Master's Table",
  "MT15.32": "The Feeding of the Four Thousand",
  "MT16.1": "The Religious Leaders Demand a Sign",
  "MT16.13": "Peter's Confesses Jesus as Christ",
  "MT16.21": "Get Behind Me, Satan!",
  "MT17.1": "The Transfiguration",
  "MT17.14": "A Demon Possessed Boy is Delivered",
  "MT17.24": "The Temple Tax",
  "MT18.1": "Who is the Greatest",
  "MT18.7": "Temptations to Sin",
  "MT18.12": "The One that Went Astray",
  "MT18.15": "The Process of Correction",
  "MT18.21": "Seventy Times Seven",
  "MT19.1": "What God Has Joined Together",
  "MT19.13": "Let the Little Children Come",
  "MT19.16": "The Rich Young Ruler",
  "MT20.1": "Workers in the Vineyard",
  "MT20.17": "They Will Condemn Him to Death",
  "MT20.20": "A Mother's Request",
  "MT20.29": "Two Blind Men Are Healed",
  "MT21.1": "The Triumphal Entry",
  "MT21.12": "The Temple is Cleansed",
  "MT21.18": "The Fig Tree Is Cursed",
  "MT21.23": "Who Gave You This Authority",
  "MT21.28": "The Will of His Father",
  "MT21.33": "The Stone That the Builders Rejected",
  "MT22.1": "The Wedding Feast",
  "MT22.15": "The Things That Are Caesar's",
  "MT22.23": "The God of the Living",
  "MT22.34": "The Great Commandment",
  "MT22.41": "Whose Son Is He?",
  "MT23.1": "Woe to You Scribes and Pharisees",
  "MT23.37": "A House Left Desolate",
  "MT24.1": "The Coming Tribulation",
  "MT24.29": "The Son of Man Coming In the Clouds",
  "MT25.1": "The Ten Virgins",
  "MT25.14": "The Tenants",
  "MT25.31": "The Sheep and the Goats",
  "MT26.1": "Conspiracy",
  "MT26.6": "The Alabaster Flask",
  "MT26.17": "The Lord's Supper",
  "MT26.30": "You Will Deny Me Three Times",
  "MT26.36": "Gethsemane",
  "MT26.57": "The House of Caiaphas",
  "MT27.1": "Jesus Before Pilate",
  "MT27.3": "How Judas Died",
  "MT27.11": "Are You the King of the Jews?",
  "MT27.15": "The People Choose Barabbas",
  "MT27.27": "Christ is Mocked",
  "MT27.32": "The Crucifixion",
  "MT27.57": "The Burial of Jesus",
  "MT28.1": "The Resurrection",
  "MT28.16": "The Great Commission",
  "MK1.1": "Prepare the Way of the Lord",
  "MK1.9": "The Baptism and Temptation",
  "MK1.16": "Follow Me",
  "MK1.21": "Jesus Heals Many",
  "MK2.1": "A Paralytic Healed",
  "MK2.13": "Levi the Tax Collector",
  "MK2.18": "Why the Disciples Didn't Fast",
  "MK2.23": "Lord of the Sabbath",
  "MK3.1": "A Man With a Withered Hand",
  "MK3.13": "The Twelve Apostles",
  "MK3.22": "Blasphemy Against the Holy Spirit",
  "MK3.31": "Who Are My Mother and My Brothers?",
  "MK4.1": "A Sower Went Out to Sow",
  "MK4.21": "A Lamp Under a Bushel",
  "MK4.26": "The Mystery of Growth",
  "MK4.35": "Peace! Be Still!",
  "MK5.1": "The Gerasene Demoniac",
  "MK5.21": "The Hem of His Garment",
  "MK5.35": "The Resurrection of Jairus's Daughter",
  "MK6.1": "Nazareth Rejects the Christ",
  "MK6.7": "The Twelve are Sent Out",
  "MK6.14": "How Jon the Baptist Died",
  "MK6.30": "The Feeding of the Five Thousand",
  "MK6.45": "Jesus Walks On Water",
  "MK6.53": "The Healings at Gennesaret",
  "MK7.1": "Their Heart is Far From Me",
  "MK7.14": "What Defiles a Person",
  "MK7.24": "The Syrophoenician Woman",
  "MK7.31": "A Deaf and Mute Man is Healed",
  "MK8.1": "The Feeding of the Four Thousand",
  "MK8.11": "The Pharisees Demand a Sign",
  "MK8.14": "The Leven of Herod and the Pharisees",
  "MK8.22": "I See Men as Trees, Walking",
  "MK8.27": "You are the Christ",
  "MK9.1": "The Transfiguration",
  "MK9.14": "The Demon Possessed Boy",
  "MK9.30": "The Death and Resurrection Foretold",
  "MK9.33": "Who Is the Greatest?",
  "MK9.38": "The One Who Is Not Against Us Is For Us",
  "MK9.42": "Hell or Amputation",
  "MK10.1": "What God Has Joined Together",
  "MK10.13": "Let the Children Come",
  "MK10.17": "The Rich Young Ruler",
  "MK10.35": "A Mother's Request",
  "MK10.46": "Blind Bartimaes",
  "MK11.1": "The Triumphal Entry",
  "MK11.12": "The Fruitless Fig Tree",
  "MK11.15": "The Cleansing of the Temple",
  "MK11.20": "A Lesson from the Fig Tree",
  "MK11.27": "The Baptism of Jon Debated",
  "MK12.1": "The Stone that the Builders Rejected",
  "MK12.13": "Paying Taxes",
  "MK12.18": "Proof of the Resurrection",
  "MK12.28": "Heart, Soul, Mind, and Strength",
  "MK12.35": "Whose Son is He?",
  "MK12.41": "The Widow's Mite",
  "MK13.1": "The Signs of the End",
  "MK13.24": "The Return of Jesus",
  "MK13.28": "The Fig Tree's Lesson",
  "MK13.32": "Stay Awake!",
  "MK14.1": "The Plan to Kill Jesus",
  "MK14.3": "The Alabaster Flask",
  "MK14.12": "The Last Supper",
  "MK14.26": "You Will Deny Me",
  "MK14.32": "Gethsemane",
  "MK14.53": "Jesus Before the Sanhedrin",
  "MK14.66": "Before the Rooster Crows Twice",
  "MK15.1": "Christ Before Pilate",
  "MK15.16": "Christ is Mocked",
  "MK15.21": "The Crucifixion",
  "MK15.42": "Joseph of Arimathea Buries Jesus",
  "MK16.1": "The Resurrection",
  "MK16.9": "Mary Magdalene at the Tomb",
  "MK16.14": "The Great Commission",
  "LK1.5": "The Birth of Jon the Baptist",
  "LK1.26": "Gabriel Visits Mary",
  "LK1.39": "Mary Visits Elizabeth",
  "LK1.46": "The Magnificat",
  "LK1.57": "The Birth of John the Baptist",
  "LK1.67": "The Prophesy of Zechariah",
  "LK2.1": "The Birth of Jesus",
  "LK2.8": "The Shepherd's Vision",
  "LK2.22": "The Prophesy of Simeon and Anna",
  "LK2.41": "The Boy Jesus In the Temple",
  "LK3.1": "The Ministry of John the Baptist",
  "LK3.23": "The Genealogy of Jesus Christ",
  "LK4.1": "Temptation In the Wilderness",
  "LK4.16": "The Spirit of the Lord is Upon Me",
  "LK4.31": "Deliverance in the Synagogue",
  "LK5.1": "Fishers of Men",
  "LK5.12": "A Leper Cleansed",
  "LK5.17": "A Paralytic is Lowered Through the Roof",
  "LK5.27": "Levi the Tax Collector",
  "LK5.33": "Why the Disciples Didn't Fast",
  "LK6.1": "Lord of the Sabbath",
  "LK6.6": "The Man With a Withered Hand",
  "LK6.12": "The Twelve Apostles",
  "LK6.17": "The Sermon On the Mount",
  "LK6.27": "Love Your Enemies",
  "LK6.37": "Do Not Judge",
  "LK6.43": "Known by it's Fruit",
  "LK6.46": "The House On the Rock",
  "LK7.1": "A Centurion's Servant is Healed",
  "LK7.11": "A Widow's Son Resurrected",
  "LK7.18": "Are You the One?",
  "LK7.36": "A Sinful Woman's Adoration",
  "LK8.1": "The Women Following Jesus",
  "LK8.4": "A Sower Went Out to Sow",
  "LK8.19": "Jesus' Mother and Brothers",
  "LK8.22": "Jesus Calms the Storm",
  "LK8.26": "The Gerasene Demoniac",
  "LK8.41": "The Hem of His Garment",
  "LK8.49": "Jairus's Daughter",
  "LK9.1": "The Twelve are Sent Out",
  "LK9.7": "Herod's Confusion",
  "LK9.10": "The Feeding of the Five Thousand",
  "LK9.18": "Peter Confesses Jesus as Christ",
  "LK9.23": "Taking Up Your Cross",
  "LK9.28": "The Transfiguration",
  "LK9.37": "A Demon Possessed Boy is Delivered",
  "LK9.46": "The Greatest In the Kingdom of Heaven",
  "LK9.49": "Permission to Call Fire From Heaven",
  "LK9.57": "The Cost of Discipleship",
  "LK10.1": "The Seventy-Two are Sent Out",
  "LK10.13": "Woe to Chorazin and Bethsaida",
  "LK10.17": "The Seventy-Two Return",
  "LK10.21": "Jesus Rejoices in the Holy Spirit",
  "LK10.25": "The Good Samaritan",
  "LK10.38": "Mary Has Chosen the Better Portion",
  "LK11.1": "The Lord's Prayer",
  "LK11.14": "A House Divided",
  "LK11.24": "How an Unclean Spirit Returns",
  "LK11.29": "The Sign of Jonah",
  "LK11.33": "Light and Darkness",
  "LK11.37": "Woe to Pharisees and Lawyers",
  "LK12.1": "The Leven of Hypocrisy",
  "LK12.4": "The Fear of God",
  "LK12.11": "The Spirit Will Teach You What to Say",
  "LK12.13": "The Foolish Rich Man",
  "LK12.22": "Do Not Be Anxious",
  "LK12.35": "An Hour You Do Not Expect",
  "LK12.49": "A Controversial Gospel",
  "LK12.54": "The Signs of the Times",
  "LK12.57": "Settle With Your Accuser",
  "LK13.1": "Unless You Repent",
  "LK13.10": "Woman, You are Loosed",
  "LK13.18": "Leaven and a Grain of Mustard Seed",
  "LK13.22": "I Do Not Know Where You Come From",
  "LK13.31": "O Jerusalem, Jerusalem",
  "LK14.1": "Healing On the Sabbath",
  "LK14.7": "Friend, Move Up Higher",
  "LK14.12": "The Great Banquet",
  "LK14.25": "Count the Cost",
  "LK15.1": "The Lost Sheep",
  "LK15.8": "The Lost Coin",
  "LK15.11": "The Prodigal Son",
  "LK16.1": "The Dishonest Servant",
  "LK16.14": "Everyone Forces His Way Into It",
  "LK16.18": "Divorce and Adultery",
  "LK17.1": "Temptations to Sin",
  "LK17.5": "Mustard Seed Faith",
  "LK17.7": "We Are Unworthy Servants",
  "LK17.11": "Were Not Ten Cleansed?",
  "LK17.20": "The Days of the Son of Man",
  "LK18.1": "The Persistent Widow",
  "LK18.9": "Pharisee and the Tax Collector",
  "LK18.15": "Let the Children Come to Me",
  "LK18.18": "The Rich Young Ruler",
  "LK18.31": "Jesus Foretells His Death and Resurrection",
  "LK18.35": "Son of David Have Mercy on Me",
  "LK19.1": "Zacchaeus",
  "LK19.11": "The Ten Minas",
  "LK19.28": "The Triumphal Entry",
  "LK19.45": "Cleansing the Temple",
  "LK20.1": "The Baptism of John, from Heaven or Man",
  "LK20.9": "The Wicked Tenants",
  "LK20.19": "The Things that are Caesars",
  "LK20.27": "The God of the Living",
  "LK20.41": "The Lord Said to My Lord",
  "LK20.45": "Beware of the Scribes",
  "LK21.1": "Two Small Copper Coins",
  "LK21.5": "How the World Will End",
  "LK22.1": "Conspiracy",
  "LK22.7": "The Passover",
  "LK22.24": "Who Is the Greatest?",
  "LK22.31": "Peter's Denial Foretold",
  "LK22.39": "Remove This Cup From Me",
  "LK22.47": "Jesus Betrayed",
  "LK22.54": "Peter Denies Christ",
  "LK22.66": "Jesus Before the Sanhedrin",
  "LK23.1": "Jesus Before Pilate",
  "LK23.6": "Jesus Before Herod",
  "LK23.26": "The Crucifixion",
  "LK24.1": "The Resurrection",
  "LK24.13": "The Road to Emmaus",
  "LK24.36": "Jesus Appears to the Disciples",
  "LK24.50": "Ascension",
  "JN1.1": "The Word Became Flesh",
  "JN1.19": "The Testimony of John the Baptist",
  "JN1.29": "Behold, the Lamb of God",
  "JN1.35": "Come and See",
  "JN1.43": "Under the Fig Tree",
  "JN2.1": "Water Into Wine",
  "JN2.13": "The Temple Merchants are Driven Out",
  "JN3.1": "Born Again",
  "JN3.16": "For God So Loved the World",
  "JN3.22": "The Decline of Jon's Ministry",
  "JN4.1": "The Woman at the Well",
  "JN4.46": "An Official's Son is Healed",
  "JN5.1": "Take Up Your Bed and Walk",
  "JN5.19": "The Son and the Father",
  "JN6.1": "The Feeding of the Five Thousand",
  "JN6.16": "Jesus Walking On the Sea",
  "JN6.22": "The Bread of Life",
  "JN6.52": "Eat My Flesh, Drink My Blood",
  "JN7.1": "Jesus at the Feast of Booths",
  "JN7.37": "Rivers of Living Water",
  "JN8.1": "A Woman Caught In the Act of Adultery",
  "JN8.12": "I Am the Light of the World",
  "JN8.31": "The Truth Will Set You Free",
  "JN8.54": "Before Abraham Was, I Am",
  "JN9.1": "The Healing of a Man Born Blind",
  "JN10.1": "The Good Shepherd",
  "JN10.31": "You are gods",
  "JN11.1": "The Resurrection of Lazarus",
  "JN11.45": "Caiaphas Prophesies",
  "JN12.1": "Mary's Adoration and Judas's Offense",
  "JN12.9": "A Plot to Kill Lazarus",
  "JN12.12": "The Triumphal Entry",
  "JN12.20": "Christ Confirmed by the Voice of God",
  "JN12.37": "They Still Did Not Believe",
  "JN13.1": "Jesus Washes His Disciple's Feet",
  "JN13.21": "Satan Enters Into Judas",
  "JN13.31": "Love One Another",
  "JN13.36": "Peter's Denial Foretold",
  "JN14.1": "I Am the Way the Truth and the Life",
  "JN14.16": "The Promise of the Holy Spirit",
  "JN15.1": "I Am the True Vine",
  "JN16.5": "The Work of the Holy Spirit",
  "JN17.1": "Jesus Prays for His Disciples",
  "JN18.1": "The Betrayal of Jesus",
  "JN18.12": "Jesus Before Caiaphas",
  "JN18.28": "Jesus Before Pilate",
  "JN19.1": "The Crucifixion",
  "JN19.38": "The Garden Tomb",
  "JN20.1": "Christ is Risen",
  "JN20.11": "Jesus Appears to Mary Magdalene",
  "JN20.19": "Jesus Appears to the Disciples",
  "JN20.24": "Doubting Thomas",
  "JN20.30": "So That You May Believe",
  "JN21.1": "Jesus By the Sea",
  "AC1.1": "The Promise of the Holy Spirit",
  "AC1.6": "The Ascension",
  "AC1.12": "Matthias Replaces Judas",
  "AC2.1": "The Holy Spirit Falls",
  "AC3.1": "The Beggar at the Gate Called Beautiful",
  "AC4.23": "Grant to Your Servants All Boldness",
  "AC5.1": "Ananias and Sapphira",
  "AC5.17": "An Angel Frees the Apostles",
  "AC5.33": "The Wisdom of Gamaliel",
  "AC6.1": "The Hellenists Complain",
  "AC6.8": "The Wisdom of Steven",
  "AC7.1": "Stephan's Soliloquy",
  "AC7.54": "The Martyrdom of Steven",
  "AC8.1": "Saul Persecutes the Church",
  "AC8.4": "Philip In Samaria",
  "AC8.9": "Simon the Magician",
  "AC8.26": "The Ethiopian Eunuch",
  "AC9.1": "The Conversion of Saul",
  "AC9.19": "Saul Begins to Proclaim Christ",
  "AC9.23": "Saul Escapes Damascus in a Basket",
  "AC9.32": "The Healing of Aeneas",
  "AC9.36": "The Resurrection of Dorcas",
  "AC10.1": "Cornelius's Vision",
  "AC10.9": "Peter's Vision",
  "AC10.44": "The Holy Spirit Falls on the Gentiles",
  "AC11.1": "Peter Recount's Cornelius's Conversion",
  "AC11.19": "The Church In Antioch",
  "AC12.1": "The Martyrdom of James",
  "AC12.6": "An Angel Rescues Peter",
  "AC12.20": "How Herod Died",
  "AC13.1": "Set Apart For Me Barnabas and Saul",
  "AC13.4": "Bar-Jesus Struck Blind",
  "AC13.13": "Paul Preaches in Antioch of Pisidia",
  "AC14.1": "Paul and Barnabus Preach in Iconium",
  "AC14.8": "A Cripple Healed at Lystra",
  "AC14.12": "Paul Survives His Stoning",
  "AC15.1": "A Debate in Jerusalem",
  "AC15.22": "The Apostles Write to Gentile Believers",
  "AC15.36": "Why Paul and Barnabus Separated",
  "AC16.1": "Timothy Joins Paul and Silas",
  "AC16.6": "Come Over to Macedonia and Help Us",
  "AC16.11": "The Conversion of Lydia",
  "AC16.16": "A Spirit Cast Out of a Slave Girl",
  "AC16.19": "Paul and Silas in Prison",
  "AC16.25": "The Jailer is Converted",
  "AC17.1": "The Believers are Fined",
  "AC17.10": "The Jews of Thessalonica",
  "AC17.16": "The Areopagus of Athens",
  "AC18.1": "Paul in Corinth",
  "AC18.12": "Paul Before Gallio",
  "AC18.18": "Paul’s Return Journey",
  "AC18.24": "The Ministry of Apollos",
  "AC19.1": "Twelve Conversions in Ephesus",
  "AC19.11": "The Seven Sons of Sceva",
  "AC19.23": "A Riot in Ephesus",
  "AC20.7": "The Resurrection of Eutychus",
  "AC20.17": "Paul’s Farewell Address",
  "AC21.1": "Paul Returns to Jerusalem",
  "AC21.17": "The Elder’s Proposition",
  "AC21.27": "Paul Arrested",
  "AC22.1": "Paul Addresses the People",
  "AC22.22": "Roman Citizenship",
  "AC23.1": "Paul Before the Council",
  "AC23.12": "A Foiled Assassination",
  "AC24.1": "Felix of Caesarea",
  "AC25.1": "The Appeal to Caesar",
  "AC25.13": "Paul Testifies to Agrippa",
  "AC26.12": "Paul Recounts His Conversion",
  "AC27.1": "A Doomed Voyage",
  "AC27.13": "The Storm",
  "AC27.21": "The Vision",
  "AC28.1": "Paul on Malta",
  "AC28.11": "Paul in Italy",
  "AC28.17": "Paul Addresses the Jews in Rome",
  "RM1.1": "Paul, A Servant of Christ",
  "RM1.8": "For I Long to See You",
  "RM1.16": "I Am Not Ashamed of the Gospel",
  "RM1.18": "Revealed Wrath",
  "RM2.1": "God’s Righteous Judgment",
  "RM2.12": "A Law Written on Hearts",
  "RM3.1": "The Faithfulness of God",
  "RM3.11": "None is Righteous",
  "RM4.1": "Abraham’s Justification",
  "RM5.1": "Faith Based Justification",
  "RM5.12": "Christ is the Second Adam",
  "RM6.1": "Dead to Sin and Alive to God",
  "RM6.16": "Slaves of Righteousness",
  "RM7.1": "Dead to the Law",
  "RM7.7": "Sold Unto Sin through the Law",
  "RM8.1": "The Law of the Spirit of Life",
  "RM8.12": "The Spirit of Adoption",
  "RM8.18": "The Coming Freedom from Decay",
  "RM8.31": "Inseparable from His Love",
  "RM9.1": "The Sovereignty of God",
  "RM10.1": "The Word of Faith",
  "RM10.20": "The Remnant of Israel’s",
  "RM11.1": "Grafted Into the Vine",
  "RM11.25": "The Reason for Their Fall",
  "RM12.1": "Living Sacrifice",
  "RM12.9": "Commandments",
  "RM13.1": "Submission to Authority",
  "RM13.8": "Love and Conduct",
  "RM14.1": "Living to the Lord",
  "RM15.13": "The Example of Christ",
  "RM15.8": "The Hope of the Gentiles",
  "RM15.14": "Paul’s Ministry to the Gentiles",
  "RM16.1": "Personal Greetings",
  "C11.4": "Thanksgiving",
  "C11.10": "Is Christ Divided?",
  "C11.18": "The Weak to Shame the Strong",
  "C12.1": "Proclaiming Christ Crucified",
  "C12.6": "Wisdom Taught by the Spirit",
  "C13.1": "How Factions Evidence Immaturity",
  "C14.1": "The Apostle’s Labor",
  "C15.1": "Sexual Immorality in the Church",
  "C16.1": "Lawsuits in the Church",
  "C16.12": "Flee From Sexual Immorality",
  "C17.1": "New Testament Marriage",
  "C17.25": "Remain Single if You Can",
  "C18.1": "The Sin of Causing Others to Stumble",
  "C19.1": "Paul Sacrifices His Rights",
  "C110.1": "Flee From Idolatry",
  "C110.23": "Give No Offence",
  "C111.2": "Head Coverings",
  "C111.17": "The Lord’s Supper",
  "C112.1": "Spiritual Gifts",
  "C112.12": "The Different Roles of the Body",
  "C113.1": "Love",
  "C114.1": "Speaking in Tongues and Prophesying",
  "C114.26": "An Orderly Worship",
  "C115.1": "The Resurrection",
  "C115.35": "The Body that is To Be",
  "C115.50": "Putting on Immortality",
  "C116.1": "The Collection for the Saints",
  "C116.12": "Travel Plans",
  "C21.3": "God of All Comfort",
  "C21.8": "Their Affliction in Asia",
  "C21.13": "An Unwavering Gospel",
  "C22.1": "Forgive the Expelled Brother",
  "C22.12": "The Leadership of Christ",
  "C23.1": "The Glory of the New Covenant",
  "C24.1": "The Image of God",
  "C24.8": "A Treasure in Earthen Vessels",
  "C25.1": "A House Not Made With Hands",
  "C25.11": "A New Creation",
  "C26.1": "Now is the Day of Salvation",
  "C26.14": "Separated from the World",
  "C27.2": "Godly Grief",
  "C28.1": "Generosity Encouraged",
  "C28.16": "A Commendation for Titus",
  "C29.1": "The Cheerful Giver",
  "C210.1": "Paul Defends His Ministry",
  "C211.1": "Preaching in Humility",
  "C211.16": "Paul’s Suffering",
  "C212.1": "The Thorn in the Flesh",
  "C213.1": "Examine Yourselves",
  "GL1.6": "The Apostate are Cursed",
  "GL1.11": "Paul’s Devine Calling",
  "GL2.1": "Paul’s Trip to Jerusalem",
  "GL2.11": "Peter’s Hypocrisy",
  "GL2.15": "Justified by Faith",
  "GL3.1": "By the Hearing of Faith",
  "GL3.10": "The Righteous Shall Live by Faith",
  "GL3.15": "The Promise of Salvation",
  "GL4.1": "Heirs through God",
  "GL4.21": "Hagar and Sarah",
  "GL5.1": "Christ Has Set Us Free",
  "GL5.16": "Walk by the Spirit",
  "GL6.1": "Bear One Another’s Burdens",
  "GL6.11": "The Futility of Circumcision",
  "EP1.6": "The Blessing of Redemption",
  "EP2.1": "Saved by Grace through Faith",
  "EP2.11": "Gentiles and Jews are Unified in Christ",
  "EP3.1": "The Mystery Hidden for Ages",
  "EP4.1": "He Gave Gifts to Men",
  "EP4.17": "A New Pattern of Living",
  "EP5.1": "Walk in Love",
  "EP5.22": "The Healthy Marriage",
  "EP6.1": "The Healthy Family",
  "EP6.5": "Slaves and Their Masters",
  "EP6.10": "The Armor of God",
  "PP1.3": "Thanksgiving",
  "PP1.12": "The Gospel is Preached",
  "PP2.1": "Imitate Christ’s Humility",
  "PP2.12": "Working Out Salvation",
  "PP3.19": "Timothy and Epaphroditus",
  "PP3.1": "The Goal",
  "PP4.1": "Exhortation",
  "PP4.10": "The Philippians’ Generosity",
  "CL1.3": "Thanksgiving",
  "CL1.13": "The Image of the Invisible God",
  "CL1.24": "The Hope of Glory",
  "CL2.1": "Built Up in Christ",
  "CL2.16": "Let No One Disqualify You",
  "CL3.1": "Seek the Things That Are Above",
  "CL4.18": "The Christian Household",
  "CL4.2": "Final Greetings",
  "H11.2": "The Thessalonians’ Example",
  "H12.1": "A Pure and Honest Gospel",
  "H13.1": "A Good Report From Timothy",
  "H14.13": "The Coming of the Lord",
  "H15.12": "Christian Conduct",
  "H21.3": "Thanksgiving",
  "H21.5": "Judgment Day",
  "H22.1": "The Antichrist",
  "H23.1": "Pray for Us",
  "H23.6": "Dealing With the Lazy",
  "H23.16": "Benediction",
  "T11.3": "Sensationalist Distractions",
  "T11.12": "Jesus Came Into the World to Save Sinners",
  "T12.1": "A Call to Prayer",
  "T13.1": "The Qualities of Church Leader",
  "T13.8": "The Qualities of a Deacon",
  "T13.14": "The Mystery of Godliness",
  "T14.1": "Some Will Depart the Faith",
  "T14.6": "Spiritual Discipline",
  "T15.1": "The Treatment of Elders and Widows",
  "T16.1": "The Conduct of Slaves",
  "T16.3": "The Love of Money",
  "T16.11": "Fight the Good Fight",
  "T21.1": "Timothy’s Faith",
  "T21.8": "Loyalty to the Faith",
  "T22.1": "A Good Soldier of Christ Jesus",
  "T22.14": "An Approved Worker",
  "T23.1": "The Godless Last Days",
  "T23.10": "All Scripture Is Breathed Out by God",
  "T24.1": "Preach the Word",
  "T24.9": "The Lord Will Rescue Me",
  "TT1.1": "The Qualifications of Elders",
  "TT2.1": "Proper Conduct",
  "TT3.1": "Ready for Every Good Work",
  "PM1.1": "A Plea for Onesimus",
  "HB1.1": "The Absolute Deity of Jesus",
  "HB2.1": "The Absolute Humanity of Jesus",
  "HB3.1": "Why Jesus is Greater Than Moses",
  "HB4.1": "A Promised Rest for God’s People",
  "HB4.14": "Our Great High Priest",
  "HB5.12": "Moving Into Maturity",
  "HB6.4": "The Danger of Falling Away",
  "HB6.13": "When God Swears by Himself",
  "HB7.1": "The Order of Melchizedek",
  "HB8.1": "A New Covenant",
  "HB9.1": "The Old Tabernacle",
  "HB10.1": "Christ’s Sacrifice Is Final",
  "HB11.1": "Faith",
  "HB12.1": "The Author and Finisher",
  "HB13.1": "Sacrifices Pleasing to God",
  "JM1.2": "Trials and Temptations",
  "JM1.19": "Living the Word",
  "JM2.1": "Show No Partiality",
  "JM2.14": "Faith Without Works",
  "JM3.1": "The Tongue is a Fire",
  "JM3.13": "Wisdom in Wickedness",
  "JM4.1": "Friendship With the World",
  "JM5.1": "The Folly of Riches",
  "JM5.7": "Patient Endurance",
  "JM5.13": "The Prayer of Faith",
  "P11.3": "A Living Hope",
  "P11.13": "Be Holy",
  "P12.1": "A Living Stone",
  "P12.13": "Submit to Authority",
  "P13.1": "To Wives and Husbands",
  "P13.8": "Do Not Repay Evil for Evil",
  "P14.1": "Holiness and Servitude",
  "P15.1": "An Exhortation to Elders",
  "P21.3": "Make Your Calling and Election Sure",
  "P22.1": "False Teachings",
  "P23.1": "The Lord’s Return",
  "J11.1": "The Word of Life",
  "J11.5": "Walk in the Light",
  "J12.1": "An Advocate With the Father",
  "J12.7": "An Old Commandment",
  "J12.15": "Love Not the World",
  "J12.18": "The Antichrist is Coming",
  "J13.1": "We Are God’s Children",
  "J13.11": "Love One Another",
  "J14.1": "Do Not Believe Every Spirit",
  "J14.7": "God Is Love",
  "J15.1": "The Victory That Has Overcome the World",
  "J15.6": "The Spirit and the Water and the Blood",
  "J15.13": "A Sin Not Leading to Death",
  "J21.4": "Walking in the Truth",
  "J31.5": "Imitate the Good",
  "JD1.3": "Blemishes on Your Love Feast",
  "JD1.24": "Doxology",
  "RV1.4": "To the Seven Churches",
  "RV1.9": "One Like the Son of Man",
  "RV2.1": "To the Church in Ephesus",
  "RV2.8": "To the Church in Smyrna",
  "RV2.12": "To the Church in Pergamum",
  "RV2.18": "To the Church in Thyatira",
  "RV3.1": "To the Church in Sardis",
  "RV3.7": "To the Church in Philadelphia",
  "RV3.14": "To the Church in Laodicea",
  "RV4.1": "The Throne of God",
  "RV5.1": "Who Is Worthy To Open the Scroll?",
  "RV6.1": "The Seven Seals",
  "RV7.1": "The 144,000",
  "RV7.9": "A Great Multitude",
  "RV8.1": "The Seventh Seal",
  "RV8.6": "The Seven Trumpets",
  "RV10.1": "The Angel With the Little Book",
  "RV11.1": "The Two Witnesses",
  "RV11.15": "The Seventh Trumpet",
  "RV12.1": "The Woman Flees the Dragon",
  "RV12.7": "The Great Dragon Thrown Down",
  "RV13.1": "The First Beast",
  "RV13.11": "The Second Beast",
  "RV14.1": "Redeemed From the Earth",
  "RV14.6": "Three Messenger Angels",
  "RV14.14": "Put In Your Sickle and Reap",
  "RV15.1": "Seven Angels with Seven Plagues",
  "RV16.1": "The Seven Bowls of the Wrath of God",
  "RV17.1": "The Harlot and the Beast",
  "RV18.1": "Fallen, Fallen is Babylon the Great",
  "RV19.1": "The Marriage Supper of the Lamb",
  "RV19.11": "Behold a White Horse",
  "RV20.1": "For a Thousand Years",
  "RV20.7": "Satan Defeated",
  "RV20.11": "A Great White Throne",
  "RV21.1": "A New Heaven and a New Earth",
  "RV22.1": "The River of Life",
  "RV22.6": "Come Lord Jesus",
};
